"""Seed Michigan city and village entities.

Michigan has ~276 cities and ~257 villages. This script creates
Entity records for each city and village.

Sources:
- Wikipedia List of municipalities in Michigan
- Michigan state government municipal listings
- alphalists.com Michigan cities list
"""

from __future__ import annotations

import re
import sys

from scraper.db import get_connection, get_cursor


def slugify(name: str) -> str:
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"[\s]+", "-", s)
    return s


# fmt: off
CITIES: list[dict] = [
    # Michigan's 276 incorporated cities with their primary county
    {"name": "Adrian", "county": "Lenawee", "type": "CITY"},
    {"name": "Albion", "county": "Calhoun", "type": "CITY"},
    {"name": "Algonac", "county": "St. Clair", "type": "CITY"},
    {"name": "Allegan", "county": "Allegan", "type": "CITY"},
    {"name": "Allen Park", "county": "Wayne", "type": "CITY"},
    {"name": "Alma", "county": "Gratiot", "type": "CITY"},
    {"name": "Alpena", "county": "Alpena", "type": "CITY"},
    {"name": "Ann Arbor", "county": "Washtenaw", "type": "CITY"},
    {"name": "Auburn Hills", "county": "Oakland", "type": "CITY"},
    {"name": "Bad Axe", "county": "Huron", "type": "CITY"},
    {"name": "Bangor", "county": "Van Buren", "type": "CITY"},
    {"name": "Battle Creek", "county": "Calhoun", "type": "CITY"},
    {"name": "Bay City", "county": "Bay", "type": "CITY"},
    {"name": "Belding", "county": "Ionia", "type": "CITY"},
    {"name": "Belleville", "county": "Wayne", "type": "CITY"},
    {"name": "Benton Harbor", "county": "Berrien", "type": "CITY"},
    {"name": "Berkley", "county": "Oakland", "type": "CITY"},
    {"name": "Bessemer", "county": "Gogebic", "type": "CITY"},
    {"name": "Big Rapids", "county": "Mecosta", "type": "CITY"},
    {"name": "Birmingham", "county": "Oakland", "type": "CITY"},
    {"name": "Bloomfield Hills", "county": "Oakland", "type": "CITY"},
    {"name": "Boyne City", "county": "Charlevoix", "type": "CITY"},
    {"name": "Bridgman", "county": "Berrien", "type": "CITY"},
    {"name": "Brighton", "county": "Livingston", "type": "CITY"},
    {"name": "Bronson", "county": "Branch", "type": "CITY"},
    {"name": "Brown City", "county": "Sanilac", "type": "CITY"},
    {"name": "Buchanan", "county": "Berrien", "type": "CITY"},
    {"name": "Burton", "county": "Genesee", "type": "CITY"},
    {"name": "Cadillac", "county": "Wexford", "type": "CITY"},
    {"name": "Caro", "county": "Tuscola", "type": "CITY"},
    {"name": "Carson City", "county": "Montcalm", "type": "CITY"},
    {"name": "Caspian", "county": "Iron", "type": "CITY"},
    {"name": "Cedar Springs", "county": "Kent", "type": "CITY"},
    {"name": "Center Line", "county": "Macomb", "type": "CITY"},
    {"name": "Charlevoix", "county": "Charlevoix", "type": "CITY"},
    {"name": "Charlotte", "county": "Eaton", "type": "CITY"},
    {"name": "Cheboygan", "county": "Cheboygan", "type": "CITY"},
    {"name": "Clare", "county": "Clare", "type": "CITY"},
    {"name": "Clawson", "county": "Oakland", "type": "CITY"},
    {"name": "Clio", "county": "Genesee", "type": "CITY"},
    {"name": "Coldwater", "county": "Branch", "type": "CITY"},
    {"name": "Coleman", "county": "Midland", "type": "CITY"},
    {"name": "Coloma", "county": "Berrien", "type": "CITY"},
    {"name": "Corunna", "county": "Shiawassee", "type": "CITY"},
    {"name": "Croswell", "county": "Sanilac", "type": "CITY"},
    {"name": "Crystal Falls", "county": "Iron", "type": "CITY"},
    {"name": "Davison", "county": "Genesee", "type": "CITY"},
    {"name": "Dearborn", "county": "Wayne", "type": "CITY"},
    {"name": "Dearborn Heights", "county": "Wayne", "type": "CITY"},
    {"name": "Detroit", "county": "Wayne", "type": "CITY"},
    {"name": "DeWitt", "county": "Clinton", "type": "CITY"},
    {"name": "Dowagiac", "county": "Cass", "type": "CITY"},
    {"name": "Durand", "county": "Shiawassee", "type": "CITY"},
    {"name": "East Grand Rapids", "county": "Kent", "type": "CITY"},
    {"name": "East Jordan", "county": "Charlevoix", "type": "CITY"},
    {"name": "East Lansing", "county": "Ingham", "type": "CITY"},
    {"name": "East Tawas", "county": "Iosco", "type": "CITY"},
    {"name": "Eastpointe", "county": "Macomb", "type": "CITY"},
    {"name": "Eaton Rapids", "county": "Eaton", "type": "CITY"},
    {"name": "Ecorse", "county": "Wayne", "type": "CITY"},
    {"name": "Escanaba", "county": "Delta", "type": "CITY"},
    {"name": "Essexville", "county": "Bay", "type": "CITY"},
    {"name": "Evart", "county": "Osceola", "type": "CITY"},
    {"name": "Farmington", "county": "Oakland", "type": "CITY"},
    {"name": "Farmington Hills", "county": "Oakland", "type": "CITY"},
    {"name": "Fenton", "county": "Genesee", "type": "CITY"},
    {"name": "Ferndale", "county": "Oakland", "type": "CITY"},
    {"name": "Ferrysburg", "county": "Ottawa", "type": "CITY"},
    {"name": "Flat Rock", "county": "Wayne", "type": "CITY"},
    {"name": "Flint", "county": "Genesee", "type": "CITY"},
    {"name": "Flushing", "county": "Genesee", "type": "CITY"},
    {"name": "Frankenmuth", "county": "Saginaw", "type": "CITY"},
    {"name": "Frankfort", "county": "Benzie", "type": "CITY"},
    {"name": "Fraser", "county": "Macomb", "type": "CITY"},
    {"name": "Fremont", "county": "Newaygo", "type": "CITY"},
    {"name": "Gaastra", "county": "Iron", "type": "CITY"},
    {"name": "Galesburg", "county": "Kalamazoo", "type": "CITY"},
    {"name": "Garden City", "county": "Wayne", "type": "CITY"},
    {"name": "Gaylord", "county": "Otsego", "type": "CITY"},
    {"name": "Gibraltar", "county": "Wayne", "type": "CITY"},
    {"name": "Gladstone", "county": "Delta", "type": "CITY"},
    {"name": "Gladwin", "county": "Gladwin", "type": "CITY"},
    {"name": "Grand Blanc", "county": "Genesee", "type": "CITY"},
    {"name": "Grand Haven", "county": "Ottawa", "type": "CITY"},
    {"name": "Grand Ledge", "county": "Eaton", "type": "CITY"},
    {"name": "Grand Rapids", "county": "Kent", "type": "CITY"},
    {"name": "Grandville", "county": "Kent", "type": "CITY"},
    {"name": "Grant", "county": "Newaygo", "type": "CITY"},
    {"name": "Grayling", "county": "Crawford", "type": "CITY"},
    {"name": "Greenville", "county": "Montcalm", "type": "CITY"},
    {"name": "Grosse Pointe", "county": "Wayne", "type": "CITY"},
    {"name": "Grosse Pointe Farms", "county": "Wayne", "type": "CITY"},
    {"name": "Grosse Pointe Park", "county": "Wayne", "type": "CITY"},
    {"name": "Grosse Pointe Woods", "county": "Wayne", "type": "CITY"},
    {"name": "Hamtramck", "county": "Wayne", "type": "CITY"},
    {"name": "Hancock", "county": "Houghton", "type": "CITY"},
    {"name": "Harbor Beach", "county": "Huron", "type": "CITY"},
    {"name": "Harbor Springs", "county": "Emmet", "type": "CITY"},
    {"name": "Harper Woods", "county": "Wayne", "type": "CITY"},
    {"name": "Harrison", "county": "Clare", "type": "CITY"},
    {"name": "Harrisville", "county": "Alcona", "type": "CITY"},
    {"name": "Hart", "county": "Oceana", "type": "CITY"},
    {"name": "Hartford", "county": "Van Buren", "type": "CITY"},
    {"name": "Hastings", "county": "Barry", "type": "CITY"},
    {"name": "Hazel Park", "county": "Oakland", "type": "CITY"},
    {"name": "Highland Park", "county": "Wayne", "type": "CITY"},
    {"name": "Hillsdale", "county": "Hillsdale", "type": "CITY"},
    {"name": "Holland", "county": "Ottawa", "type": "CITY"},
    {"name": "Houghton", "county": "Houghton", "type": "CITY"},
    {"name": "Howell", "county": "Livingston", "type": "CITY"},
    {"name": "Hudson", "county": "Lenawee", "type": "CITY"},
    {"name": "Hudsonville", "county": "Ottawa", "type": "CITY"},
    {"name": "Huntington Woods", "county": "Oakland", "type": "CITY"},
    {"name": "Imlay City", "county": "Lapeer", "type": "CITY"},
    {"name": "Inkster", "county": "Wayne", "type": "CITY"},
    {"name": "Ionia", "county": "Ionia", "type": "CITY"},
    {"name": "Iron Mountain", "county": "Dickinson", "type": "CITY"},
    {"name": "Iron River", "county": "Iron", "type": "CITY"},
    {"name": "Ironwood", "county": "Gogebic", "type": "CITY"},
    {"name": "Ishpeming", "county": "Marquette", "type": "CITY"},
    {"name": "Ithaca", "county": "Gratiot", "type": "CITY"},
    {"name": "Jackson", "county": "Jackson", "type": "CITY"},
    {"name": "Kalamazoo", "county": "Kalamazoo", "type": "CITY"},
    {"name": "Keego Harbor", "county": "Oakland", "type": "CITY"},
    {"name": "Kentwood", "county": "Kent", "type": "CITY"},
    {"name": "Kingsford", "county": "Dickinson", "type": "CITY"},
    {"name": "Lake Angelus", "county": "Oakland", "type": "CITY"},
    {"name": "Lake City", "county": "Missaukee", "type": "CITY"},
    {"name": "Lansing", "county": "Ingham", "type": "CITY"},
    {"name": "Lapeer", "county": "Lapeer", "type": "CITY"},
    {"name": "Lathrup Village", "county": "Oakland", "type": "CITY"},
    {"name": "Leslie", "county": "Ingham", "type": "CITY"},
    {"name": "Lincoln Park", "county": "Wayne", "type": "CITY"},
    {"name": "Linden", "county": "Genesee", "type": "CITY"},
    {"name": "Litchfield", "county": "Hillsdale", "type": "CITY"},
    {"name": "Livonia", "county": "Wayne", "type": "CITY"},
    {"name": "Lowell", "county": "Kent", "type": "CITY"},
    {"name": "Ludington", "county": "Mason", "type": "CITY"},
    {"name": "Luna Pier", "county": "Monroe", "type": "CITY"},
    {"name": "Madison Heights", "county": "Oakland", "type": "CITY"},
    {"name": "Manistee", "county": "Manistee", "type": "CITY"},
    {"name": "Manistique", "county": "Schoolcraft", "type": "CITY"},
    {"name": "Manton", "county": "Wexford", "type": "CITY"},
    {"name": "Marine City", "county": "St. Clair", "type": "CITY"},
    {"name": "Marlette", "county": "Sanilac", "type": "CITY"},
    {"name": "Marquette", "county": "Marquette", "type": "CITY"},
    {"name": "Marshall", "county": "Calhoun", "type": "CITY"},
    {"name": "Marysville", "county": "St. Clair", "type": "CITY"},
    {"name": "Mason", "county": "Ingham", "type": "CITY"},
    {"name": "Melvindale", "county": "Wayne", "type": "CITY"},
    {"name": "Memphis", "county": "St. Clair", "type": "CITY"},
    {"name": "Menominee", "county": "Menominee", "type": "CITY"},
    {"name": "Midland", "county": "Midland", "type": "CITY"},
    {"name": "Milan", "county": "Monroe", "type": "CITY"},
    {"name": "Monroe", "county": "Monroe", "type": "CITY"},
    {"name": "Montague", "county": "Muskegon", "type": "CITY"},
    {"name": "Montrose", "county": "Genesee", "type": "CITY"},
    {"name": "Morenci", "county": "Lenawee", "type": "CITY"},
    {"name": "Mount Clemens", "county": "Macomb", "type": "CITY"},
    {"name": "Mount Morris", "county": "Genesee", "type": "CITY"},
    {"name": "Mount Pleasant", "county": "Isabella", "type": "CITY"},
    {"name": "Munising", "county": "Alger", "type": "CITY"},
    {"name": "Muskegon", "county": "Muskegon", "type": "CITY"},
    {"name": "Muskegon Heights", "county": "Muskegon", "type": "CITY"},
    {"name": "Negaunee", "county": "Marquette", "type": "CITY"},
    {"name": "New Baltimore", "county": "Macomb", "type": "CITY"},
    {"name": "New Buffalo", "county": "Berrien", "type": "CITY"},
    {"name": "Newaygo", "county": "Newaygo", "type": "CITY"},
    {"name": "Niles", "county": "Berrien", "type": "CITY"},
    {"name": "North Muskegon", "county": "Muskegon", "type": "CITY"},
    {"name": "Northville", "county": "Wayne", "type": "CITY"},
    {"name": "Norton Shores", "county": "Muskegon", "type": "CITY"},
    {"name": "Norway", "county": "Dickinson", "type": "CITY"},
    {"name": "Novi", "county": "Oakland", "type": "CITY"},
    {"name": "Oak Park", "county": "Oakland", "type": "CITY"},
    {"name": "Onaway", "county": "Presque Isle", "type": "CITY"},
    {"name": "Orchard Lake Village", "county": "Oakland", "type": "CITY"},
    {"name": "Otsego", "county": "Allegan", "type": "CITY"},
    {"name": "Ovid", "county": "Clinton", "type": "CITY"},
    {"name": "Owosso", "county": "Shiawassee", "type": "CITY"},
    {"name": "Parchment", "county": "Kalamazoo", "type": "CITY"},
    {"name": "Perry", "county": "Shiawassee", "type": "CITY"},
    {"name": "Petersburg", "county": "Monroe", "type": "CITY"},
    {"name": "Petoskey", "county": "Emmet", "type": "CITY"},
    {"name": "Pinconning", "county": "Bay", "type": "CITY"},
    {"name": "Plainwell", "county": "Allegan", "type": "CITY"},
    {"name": "Pleasant Ridge", "county": "Oakland", "type": "CITY"},
    {"name": "Plymouth", "county": "Wayne", "type": "CITY"},
    {"name": "Pontiac", "county": "Oakland", "type": "CITY"},
    {"name": "Portage", "county": "Kalamazoo", "type": "CITY"},
    {"name": "Port Huron", "county": "St. Clair", "type": "CITY"},
    {"name": "Portland", "county": "Ionia", "type": "CITY"},
    {"name": "Potterville", "county": "Eaton", "type": "CITY"},
    {"name": "Reading", "county": "Hillsdale", "type": "CITY"},
    {"name": "Reed City", "county": "Osceola", "type": "CITY"},
    {"name": "Richmond", "county": "Macomb", "type": "CITY"},
    {"name": "River Rouge", "county": "Wayne", "type": "CITY"},
    {"name": "Riverview", "county": "Wayne", "type": "CITY"},
    {"name": "Rochester", "county": "Oakland", "type": "CITY"},
    {"name": "Rochester Hills", "county": "Oakland", "type": "CITY"},
    {"name": "Rockford", "county": "Kent", "type": "CITY"},
    {"name": "Rockwood", "county": "Wayne", "type": "CITY"},
    {"name": "Rogers City", "county": "Presque Isle", "type": "CITY"},
    {"name": "Romulus", "county": "Wayne", "type": "CITY"},
    {"name": "Roosevelt Park", "county": "Muskegon", "type": "CITY"},
    {"name": "Roseville", "county": "Macomb", "type": "CITY"},
    {"name": "Royal Oak", "county": "Oakland", "type": "CITY"},
    {"name": "Saginaw", "county": "Saginaw", "type": "CITY"},
    {"name": "St. Charles", "county": "Saginaw", "type": "CITY"},
    {"name": "St. Clair", "county": "St. Clair", "type": "CITY"},
    {"name": "St. Clair Shores", "county": "Macomb", "type": "CITY"},
    {"name": "St. Ignace", "county": "Mackinac", "type": "CITY"},
    {"name": "St. Johns", "county": "Clinton", "type": "CITY"},
    {"name": "St. Joseph", "county": "Berrien", "type": "CITY"},
    {"name": "St. Louis", "county": "Gratiot", "type": "CITY"},
    {"name": "Saline", "county": "Washtenaw", "type": "CITY"},
    {"name": "Sandusky", "county": "Sanilac", "type": "CITY"},
    {"name": "Sault Ste. Marie", "county": "Chippewa", "type": "CITY"},
    {"name": "Scottville", "county": "Mason", "type": "CITY"},
    {"name": "South Haven", "county": "Van Buren", "type": "CITY"},
    {"name": "South Lyon", "county": "Oakland", "type": "CITY"},
    {"name": "Southfield", "county": "Oakland", "type": "CITY"},
    {"name": "Southgate", "county": "Wayne", "type": "CITY"},
    {"name": "Springfield", "county": "Calhoun", "type": "CITY"},
    {"name": "Stambaugh", "county": "Iron", "type": "CITY"},
    {"name": "Standish", "county": "Arenac", "type": "CITY"},
    {"name": "Stanton", "county": "Montcalm", "type": "CITY"},
    {"name": "Sterling Heights", "county": "Macomb", "type": "CITY"},
    {"name": "Sturgis", "county": "St. Joseph", "type": "CITY"},
    {"name": "Swartz Creek", "county": "Genesee", "type": "CITY"},
    {"name": "Sylvan Lake", "county": "Oakland", "type": "CITY"},
    {"name": "Tawas City", "county": "Iosco", "type": "CITY"},
    {"name": "Taylor", "county": "Wayne", "type": "CITY"},
    {"name": "Tecumseh", "county": "Lenawee", "type": "CITY"},
    {"name": "Three Rivers", "county": "St. Joseph", "type": "CITY"},
    {"name": "Traverse City", "county": "Grand Traverse", "type": "CITY"},
    {"name": "Trenton", "county": "Wayne", "type": "CITY"},
    {"name": "Troy", "county": "Oakland", "type": "CITY"},
    {"name": "Utica", "county": "Macomb", "type": "CITY"},
    {"name": "Vassar", "county": "Tuscola", "type": "CITY"},
    {"name": "Wakefield", "county": "Gogebic", "type": "CITY"},
    {"name": "Walker", "county": "Kent", "type": "CITY"},
    {"name": "Walled Lake", "county": "Oakland", "type": "CITY"},
    {"name": "Warren", "county": "Macomb", "type": "CITY"},
    {"name": "Wayne", "county": "Wayne", "type": "CITY"},
    {"name": "Westland", "county": "Wayne", "type": "CITY"},
    {"name": "White Cloud", "county": "Newaygo", "type": "CITY"},
    {"name": "Whitehall", "county": "Muskegon", "type": "CITY"},
    {"name": "Williamston", "county": "Ingham", "type": "CITY"},
    {"name": "Wixom", "county": "Oakland", "type": "CITY"},
    {"name": "Woodhaven", "county": "Wayne", "type": "CITY"},
    {"name": "Wyandotte", "county": "Wayne", "type": "CITY"},
    {"name": "Wyoming", "county": "Kent", "type": "CITY"},
    {"name": "Yale", "county": "St. Clair", "type": "CITY"},
    {"name": "Ypsilanti", "county": "Washtenaw", "type": "CITY"},
    {"name": "Zeeland", "county": "Ottawa", "type": "CITY"},
    {"name": "Zilwaukee", "county": "Saginaw", "type": "CITY"},
    {"name": "Atlanta", "county": "Montmorency", "type": "CITY"},
    {"name": "Au Gres", "county": "Arenac", "type": "CITY"},
    {"name": "Auburn", "county": "Bay", "type": "CITY"},
    {"name": "Beaverton", "county": "Gladwin", "type": "CITY"},
    {"name": "Coopersville", "county": "Ottawa", "type": "CITY"},
    {"name": "Covert", "county": "Van Buren", "type": "CITY"},
    {"name": "Gobles", "county": "Van Buren", "type": "CITY"},
    {"name": "Grosse Pointe Shores", "county": "Wayne", "type": "CITY"},
    {"name": "Lanse Creuse", "county": "Macomb", "type": "CITY"},
    {"name": "Mio", "county": "Oscoda", "type": "CITY"},
    {"name": "Napoleon", "county": "Jackson", "type": "CITY"},
    {"name": "Omer", "county": "Arenac", "type": "CITY"},
    {"name": "Rose City", "county": "Ogemaw", "type": "CITY"},
    {"name": "Saugatuck", "county": "Allegan", "type": "CITY"},
    {"name": "Stephenson", "county": "Menominee", "type": "CITY"},
    {"name": "West Branch", "county": "Ogemaw", "type": "CITY"},
    {"name": "Sanford", "county": "Midland", "type": "CITY"},
    {"name": "Saranac", "county": "Ionia", "type": "CITY"},
    {"name": "Argentine", "county": "Genesee", "type": "CITY"},
    {"name": "Bridgeport", "county": "Saginaw", "type": "CITY"},
    {"name": "Carrollton", "county": "Saginaw", "type": "CITY"},
    {"name": "Clinton", "county": "Lenawee", "type": "CITY"},
]

VILLAGES: list[dict] = [
    # Michigan's ~257 incorporated villages with their primary county
    {"name": "Addison", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "Ahmeek", "county": "Keweenaw", "type": "VILLAGE"},
    {"name": "Akron", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Alanson", "county": "Emmet", "type": "VILLAGE"},
    {"name": "Allen", "county": "Hillsdale", "type": "VILLAGE"},
    {"name": "Almont", "county": "Lapeer", "type": "VILLAGE"},
    {"name": "Alpha", "county": "Iron", "type": "VILLAGE"},
    {"name": "Applegate", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Armada", "county": "Macomb", "type": "VILLAGE"},
    {"name": "Ashley", "county": "Gratiot", "type": "VILLAGE"},
    {"name": "Athens", "county": "Calhoun", "type": "VILLAGE"},
    {"name": "Baldwin", "county": "Lake", "type": "VILLAGE"},
    {"name": "Bancroft", "county": "Shiawassee", "type": "VILLAGE"},
    {"name": "Baraga", "county": "Baraga", "type": "VILLAGE"},
    {"name": "Baroda", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Barryton", "county": "Mecosta", "type": "VILLAGE"},
    {"name": "Barton Hills", "county": "Washtenaw", "type": "VILLAGE"},
    {"name": "Bear Lake", "county": "Manistee", "type": "VILLAGE"},
    {"name": "Bellaire", "county": "Antrim", "type": "VILLAGE"},
    {"name": "Bellevue", "county": "Eaton", "type": "VILLAGE"},
    {"name": "Benzonia", "county": "Benzie", "type": "VILLAGE"},
    {"name": "Berrien Springs", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Beulah", "county": "Benzie", "type": "VILLAGE"},
    {"name": "Beverly Hills", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Bingham Farms", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Birch Run", "county": "Saginaw", "type": "VILLAGE"},
    {"name": "Blissfield", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "Bloomingdale", "county": "Van Buren", "type": "VILLAGE"},
    {"name": "Boyne Falls", "county": "Charlevoix", "type": "VILLAGE"},
    {"name": "Breckenridge", "county": "Gratiot", "type": "VILLAGE"},
    {"name": "Breedsville", "county": "Van Buren", "type": "VILLAGE"},
    {"name": "Britton", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "Brooklyn", "county": "Jackson", "type": "VILLAGE"},
    {"name": "Burlington", "county": "Calhoun", "type": "VILLAGE"},
    {"name": "Burr Oak", "county": "St. Joseph", "type": "VILLAGE"},
    {"name": "Byron", "county": "Shiawassee", "type": "VILLAGE"},
    {"name": "Caledonia", "county": "Kent", "type": "VILLAGE"},
    {"name": "Calumet", "county": "Houghton", "type": "VILLAGE"},
    {"name": "Camden", "county": "Hillsdale", "type": "VILLAGE"},
    {"name": "Carney", "county": "Menominee", "type": "VILLAGE"},
    {"name": "Caseville", "county": "Huron", "type": "VILLAGE"},
    {"name": "Casnovia", "county": "Muskegon", "type": "VILLAGE"},
    {"name": "Cass City", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Cassopolis", "county": "Cass", "type": "VILLAGE"},
    {"name": "Cement City", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "Central Lake", "county": "Antrim", "type": "VILLAGE"},
    {"name": "Centreville", "county": "St. Joseph", "type": "VILLAGE"},
    {"name": "Chatham", "county": "Alger", "type": "VILLAGE"},
    {"name": "Chelsea", "county": "Washtenaw", "type": "VILLAGE"},
    {"name": "Chesaning", "county": "Saginaw", "type": "VILLAGE"},
    {"name": "Clarkston", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Clarksville", "county": "Ionia", "type": "VILLAGE"},
    {"name": "Clayton", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "Clifford", "county": "Lapeer", "type": "VILLAGE"},
    {"name": "Climax", "county": "Kalamazoo", "type": "VILLAGE"},
    {"name": "Clinton", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "Columbiaville", "county": "Lapeer", "type": "VILLAGE"},
    {"name": "Concord", "county": "Jackson", "type": "VILLAGE"},
    {"name": "Constantine", "county": "St. Joseph", "type": "VILLAGE"},
    {"name": "Copemish", "county": "Manistee", "type": "VILLAGE"},
    {"name": "Copper City", "county": "Houghton", "type": "VILLAGE"},
    {"name": "Custer", "county": "Mason", "type": "VILLAGE"},
    {"name": "Daggett", "county": "Menominee", "type": "VILLAGE"},
    {"name": "Dansville", "county": "Ingham", "type": "VILLAGE"},
    {"name": "Decatur", "county": "Van Buren", "type": "VILLAGE"},
    {"name": "Deckerville", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Deerfield", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "De Tour Village", "county": "Chippewa", "type": "VILLAGE"},
    {"name": "Dexter", "county": "Washtenaw", "type": "VILLAGE"},
    {"name": "Dimondale", "county": "Eaton", "type": "VILLAGE"},
    {"name": "Douglas", "county": "Allegan", "type": "VILLAGE"},
    {"name": "Dryden", "county": "Lapeer", "type": "VILLAGE"},
    {"name": "Dundee", "county": "Monroe", "type": "VILLAGE"},
    {"name": "Eagle", "county": "Clinton", "type": "VILLAGE"},
    {"name": "Eastlake", "county": "Manistee", "type": "VILLAGE"},
    {"name": "Eau Claire", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Edmore", "county": "Montcalm", "type": "VILLAGE"},
    {"name": "Edwardsburg", "county": "Cass", "type": "VILLAGE"},
    {"name": "Elberta", "county": "Benzie", "type": "VILLAGE"},
    {"name": "Elk Rapids", "county": "Antrim", "type": "VILLAGE"},
    {"name": "Elkton", "county": "Huron", "type": "VILLAGE"},
    {"name": "Ellsworth", "county": "Antrim", "type": "VILLAGE"},
    {"name": "Elsie", "county": "Clinton", "type": "VILLAGE"},
    {"name": "Emmett", "county": "St. Clair", "type": "VILLAGE"},
    {"name": "Empire", "county": "Leelanau", "type": "VILLAGE"},
    {"name": "Estral Beach", "county": "Monroe", "type": "VILLAGE"},
    {"name": "Fairgrove", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Fife Lake", "county": "Grand Traverse", "type": "VILLAGE"},
    {"name": "Forestville", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Fountain", "county": "Mason", "type": "VILLAGE"},
    {"name": "Fowler", "county": "Clinton", "type": "VILLAGE"},
    {"name": "Fowlerville", "county": "Livingston", "type": "VILLAGE"},
    {"name": "Franklin", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Free Soil", "county": "Mason", "type": "VILLAGE"},
    {"name": "Freeport", "county": "Barry", "type": "VILLAGE"},
    {"name": "Fruitport", "county": "Muskegon", "type": "VILLAGE"},
    {"name": "Gagetown", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Gaines", "county": "Genesee", "type": "VILLAGE"},
    {"name": "Galien", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Garden", "county": "Delta", "type": "VILLAGE"},
    {"name": "Goodrich", "county": "Genesee", "type": "VILLAGE"},
    {"name": "Grand Beach", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Grass Lake", "county": "Jackson", "type": "VILLAGE"},
    {"name": "Grosse Pointe Shores", "county": "Wayne", "type": "VILLAGE"},
    {"name": "Hanover", "county": "Jackson", "type": "VILLAGE"},
    {"name": "Harrietta", "county": "Wexford", "type": "VILLAGE"},
    {"name": "Hersey", "county": "Osceola", "type": "VILLAGE"},
    {"name": "Hesperia", "county": "Oceana", "type": "VILLAGE"},
    {"name": "Hillman", "county": "Montmorency", "type": "VILLAGE"},
    {"name": "Holly", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Homer", "county": "Calhoun", "type": "VILLAGE"},
    {"name": "Honor", "county": "Benzie", "type": "VILLAGE"},
    {"name": "Hopkins", "county": "Allegan", "type": "VILLAGE"},
    {"name": "Howard City", "county": "Montcalm", "type": "VILLAGE"},
    {"name": "Hubbardston", "county": "Ionia", "type": "VILLAGE"},
    {"name": "Jonesville", "county": "Hillsdale", "type": "VILLAGE"},
    {"name": "Kaleva", "county": "Manistee", "type": "VILLAGE"},
    {"name": "Kalkaska", "county": "Kalkaska", "type": "VILLAGE"},
    {"name": "Kent City", "county": "Kent", "type": "VILLAGE"},
    {"name": "Kinde", "county": "Huron", "type": "VILLAGE"},
    {"name": "Kingsley", "county": "Grand Traverse", "type": "VILLAGE"},
    {"name": "Kingston", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "L'Anse", "county": "Baraga", "type": "VILLAGE"},
    {"name": "Lake Ann", "county": "Benzie", "type": "VILLAGE"},
    {"name": "Lake Isabella", "county": "Isabella", "type": "VILLAGE"},
    {"name": "Lake Linden", "county": "Houghton", "type": "VILLAGE"},
    {"name": "Lake Odessa", "county": "Ionia", "type": "VILLAGE"},
    {"name": "Lake Orion", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Lakeview", "county": "Montcalm", "type": "VILLAGE"},
    {"name": "Lakewood Club", "county": "Muskegon", "type": "VILLAGE"},
    {"name": "Laurium", "county": "Houghton", "type": "VILLAGE"},
    {"name": "Lawrence", "county": "Van Buren", "type": "VILLAGE"},
    {"name": "Lawton", "county": "Van Buren", "type": "VILLAGE"},
    {"name": "Lennon", "county": "Shiawassee", "type": "VILLAGE"},
    {"name": "Leonard", "county": "Oakland", "type": "VILLAGE"},
    {"name": "LeRoy", "county": "Osceola", "type": "VILLAGE"},
    {"name": "Lexington", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Lincoln", "county": "Alcona", "type": "VILLAGE"},
    {"name": "Luther", "county": "Lake", "type": "VILLAGE"},
    {"name": "Lyons", "county": "Ionia", "type": "VILLAGE"},
    {"name": "McBain", "county": "Missaukee", "type": "VILLAGE"},
    {"name": "McBride", "county": "Montcalm", "type": "VILLAGE"},
    {"name": "Mackinac Island", "county": "Mackinac", "type": "VILLAGE"},
    {"name": "Mackinaw City", "county": "Emmet", "type": "VILLAGE"},
    {"name": "Mancelona", "county": "Antrim", "type": "VILLAGE"},
    {"name": "Manchester", "county": "Washtenaw", "type": "VILLAGE"},
    {"name": "Maple Rapids", "county": "Clinton", "type": "VILLAGE"},
    {"name": "Marcellus", "county": "Cass", "type": "VILLAGE"},
    {"name": "Marion", "county": "Osceola", "type": "VILLAGE"},
    {"name": "Martin", "county": "Allegan", "type": "VILLAGE"},
    {"name": "Mattawan", "county": "Van Buren", "type": "VILLAGE"},
    {"name": "Maybee", "county": "Monroe", "type": "VILLAGE"},
    {"name": "Mayville", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Mecosta", "county": "Mecosta", "type": "VILLAGE"},
    {"name": "Melvin", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Mendon", "county": "St. Joseph", "type": "VILLAGE"},
    {"name": "Merrill", "county": "Saginaw", "type": "VILLAGE"},
    {"name": "Mesick", "county": "Wexford", "type": "VILLAGE"},
    {"name": "Metamora", "county": "Lapeer", "type": "VILLAGE"},
    {"name": "Michiana", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Middleville", "county": "Barry", "type": "VILLAGE"},
    {"name": "Milford", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Millersburg", "county": "Presque Isle", "type": "VILLAGE"},
    {"name": "Millington", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Minden City", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Montgomery", "county": "Hillsdale", "type": "VILLAGE"},
    {"name": "Morley", "county": "Mecosta", "type": "VILLAGE"},
    {"name": "Morrice", "county": "Shiawassee", "type": "VILLAGE"},
    {"name": "Muir", "county": "Ionia", "type": "VILLAGE"},
    {"name": "Mulliken", "county": "Eaton", "type": "VILLAGE"},
    {"name": "Nashville", "county": "Barry", "type": "VILLAGE"},
    {"name": "Newberry", "county": "Luce", "type": "VILLAGE"},
    {"name": "New Era", "county": "Oceana", "type": "VILLAGE"},
    {"name": "New Haven", "county": "Macomb", "type": "VILLAGE"},
    {"name": "New Lothrop", "county": "Shiawassee", "type": "VILLAGE"},
    {"name": "North Adams", "county": "Hillsdale", "type": "VILLAGE"},
    {"name": "North Branch", "county": "Lapeer", "type": "VILLAGE"},
    {"name": "Northport", "county": "Leelanau", "type": "VILLAGE"},
    {"name": "Oakley", "county": "Saginaw", "type": "VILLAGE"},
    {"name": "Onekama", "county": "Manistee", "type": "VILLAGE"},
    {"name": "Onsted", "county": "Lenawee", "type": "VILLAGE"},
    {"name": "Ontonagon", "county": "Ontonagon", "type": "VILLAGE"},
    {"name": "Ortonville", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Otisville", "county": "Genesee", "type": "VILLAGE"},
    {"name": "Otter Lake", "county": "Lapeer", "type": "VILLAGE"},
    {"name": "Owendale", "county": "Huron", "type": "VILLAGE"},
    {"name": "Oxford", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Parma", "county": "Jackson", "type": "VILLAGE"},
    {"name": "Paw Paw", "county": "Van Buren", "type": "VILLAGE"},
    {"name": "Peck", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Pellston", "county": "Emmet", "type": "VILLAGE"},
    {"name": "Pentwater", "county": "Oceana", "type": "VILLAGE"},
    {"name": "Perrinton", "county": "Gratiot", "type": "VILLAGE"},
    {"name": "Pewamo", "county": "Ionia", "type": "VILLAGE"},
    {"name": "Pierson", "county": "Montcalm", "type": "VILLAGE"},
    {"name": "Pigeon", "county": "Huron", "type": "VILLAGE"},
    {"name": "Pinckney", "county": "Livingston", "type": "VILLAGE"},
    {"name": "Port Austin", "county": "Huron", "type": "VILLAGE"},
    {"name": "Port Hope", "county": "Huron", "type": "VILLAGE"},
    {"name": "Port Sanilac", "county": "Sanilac", "type": "VILLAGE"},
    {"name": "Posen", "county": "Presque Isle", "type": "VILLAGE"},
    {"name": "Powers", "county": "Menominee", "type": "VILLAGE"},
    {"name": "Prescott", "county": "Ogemaw", "type": "VILLAGE"},
    {"name": "Quincy", "county": "Branch", "type": "VILLAGE"},
    {"name": "Ravenna", "county": "Muskegon", "type": "VILLAGE"},
    {"name": "Reese", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Richland", "county": "Kalamazoo", "type": "VILLAGE"},
    {"name": "Romeo", "county": "Macomb", "type": "VILLAGE"},
    {"name": "Roscommon", "county": "Roscommon", "type": "VILLAGE"},
    {"name": "Rosebush", "county": "Isabella", "type": "VILLAGE"},
    {"name": "Rothbury", "county": "Oceana", "type": "VILLAGE"},
    {"name": "Sand Lake", "county": "Kent", "type": "VILLAGE"},
    {"name": "Schoolcraft", "county": "Kalamazoo", "type": "VILLAGE"},
    {"name": "Sebewaing", "county": "Huron", "type": "VILLAGE"},
    {"name": "Shelby", "county": "Oceana", "type": "VILLAGE"},
    {"name": "Shepherd", "county": "Isabella", "type": "VILLAGE"},
    {"name": "Sheridan", "county": "Montcalm", "type": "VILLAGE"},
    {"name": "Sherwood", "county": "Branch", "type": "VILLAGE"},
    {"name": "Shoreham", "county": "Berrien", "type": "VILLAGE"},
    {"name": "South Range", "county": "Houghton", "type": "VILLAGE"},
    {"name": "South Rockwood", "county": "Monroe", "type": "VILLAGE"},
    {"name": "Sparta", "county": "Kent", "type": "VILLAGE"},
    {"name": "Spring Lake", "county": "Ottawa", "type": "VILLAGE"},
    {"name": "Springport", "county": "Jackson", "type": "VILLAGE"},
    {"name": "Stanwood", "county": "Mecosta", "type": "VILLAGE"},
    {"name": "Sterling", "county": "Arenac", "type": "VILLAGE"},
    {"name": "Stevensville", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Stockbridge", "county": "Ingham", "type": "VILLAGE"},
    {"name": "Sunfield", "county": "Eaton", "type": "VILLAGE"},
    {"name": "Suttons Bay", "county": "Leelanau", "type": "VILLAGE"},
    {"name": "Tekonsha", "county": "Calhoun", "type": "VILLAGE"},
    {"name": "Thompsonville", "county": "Benzie", "type": "VILLAGE"},
    {"name": "Three Oaks", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Turner", "county": "Arenac", "type": "VILLAGE"},
    {"name": "Tustin", "county": "Osceola", "type": "VILLAGE"},
    {"name": "Twining", "county": "Arenac", "type": "VILLAGE"},
    {"name": "Ubly", "county": "Huron", "type": "VILLAGE"},
    {"name": "Union City", "county": "Branch", "type": "VILLAGE"},
    {"name": "Unionville", "county": "Tuscola", "type": "VILLAGE"},
    {"name": "Vandalia", "county": "Cass", "type": "VILLAGE"},
    {"name": "Vanderbilt", "county": "Otsego", "type": "VILLAGE"},
    {"name": "Vermontville", "county": "Eaton", "type": "VILLAGE"},
    {"name": "Vernon", "county": "Shiawassee", "type": "VILLAGE"},
    {"name": "Vicksburg", "county": "Kalamazoo", "type": "VILLAGE"},
    {"name": "Waldron", "county": "Hillsdale", "type": "VILLAGE"},
    {"name": "Walkerville", "county": "Oceana", "type": "VILLAGE"},
    {"name": "Watervliet", "county": "Berrien", "type": "VILLAGE"},
    {"name": "Webberville", "county": "Ingham", "type": "VILLAGE"},
    {"name": "Westphalia", "county": "Clinton", "type": "VILLAGE"},
    {"name": "White Pigeon", "county": "St. Joseph", "type": "VILLAGE"},
    {"name": "Wolverine", "county": "Cheboygan", "type": "VILLAGE"},
    {"name": "Wolverine Lake", "county": "Oakland", "type": "VILLAGE"},
    {"name": "Woodland", "county": "Barry", "type": "VILLAGE"},
    {"name": "Colon", "county": "St. Joseph", "type": "VILLAGE"},
    {"name": "Ovid", "county": "Clinton", "type": "VILLAGE"},
    {"name": "St. Charles", "county": "Saginaw", "type": "VILLAGE"},
]
# fmt: on


def main() -> None:
    conn = get_connection()
    created = 0
    skipped = 0
    errors = 0

    all_entities = CITIES + VILLAGES

    try:
        with get_cursor(conn) as cur:
            # Build county lookup: name -> id
            cur.execute('SELECT id, name FROM "County" ORDER BY name')
            rows = cur.fetchall()
            if not rows:
                print("ERROR: No counties found in database. Run county seed first.")
                sys.exit(1)

            county_map: dict[str, str] = {}
            for r in rows:
                county_map[r["name"]] = r["id"]
            print(f"Found {len(county_map)} counties in database")

            for ent in all_entities:
                name = ent["name"]
                county_name = ent["county"]
                ent_type = ent["type"]
                slug = slugify(name)
                entity_id = f"ent_{slug}"

                county_id = county_map.get(county_name)
                if county_id is None:
                    print(f"  WARNING: county '{county_name}' not found for {name}")
                    errors += 1
                    continue

                # Handle potential slug collisions (same name in different counties)
                cur.execute(
                    'SELECT id FROM "Entity" WHERE slug = %s', (slug,)
                )
                existing = cur.fetchone()
                if existing:
                    slug = slugify(f"{name} {county_name}")
                    entity_id = f"ent_{slug}"

                cur.execute(
                    """
                    INSERT INTO "Entity" (
                        id, name, slug, type, platform, "countyId",
                        "scrapeStatus", "scrapeFrequency", "isCharter",
                        "createdAt", "updatedAt"
                    ) VALUES (
                        %s, %s, %s, %s, 'UNKNOWN', %s,
                        'PENDING', 24, false,
                        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    )
                    ON CONFLICT (slug) DO NOTHING
                    RETURNING id
                    """,
                    (entity_id, name, slug, ent_type, county_id),
                )
                row = cur.fetchone()
                if row:
                    created += 1
                else:
                    skipped += 1

                if (created + skipped + errors) % 50 == 0:
                    print(f"  ... processed {created + skipped + errors} entities")

        city_count = len(CITIES)
        village_count = len(VILLAGES)
        print(f"\nCity/Village entities: {created} created, {skipped} already existed, {errors} errors")
        print(f"Total cities in list: {city_count}")
        print(f"Total villages in list: {village_count}")
        print(f"Combined total: {city_count + village_count}")

    finally:
        conn.close()


if __name__ == "__main__":
    main()
