"""Seed Michigan township entities.

Michigan has ~1,240 townships across 83 counties. This script creates
Entity records for each township.

Sources:
- Michigan State University Geography of Michigan project
- Michigan Townships Association
- Wikipedia List of townships in Michigan
"""

from __future__ import annotations

import re
import sys

from scraper.db import get_connection, get_cursor


def slugify(name: str) -> str:
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"[\s]+", "-", s)
    return s


# fmt: off
TOWNSHIPS: list[dict] = [
    # Alcona County (11)
    {"name": "Alcona Township", "county": "Alcona"},
    {"name": "Caledonia Township", "county": "Alcona"},
    {"name": "Curtis Township", "county": "Alcona"},
    {"name": "Greenbush Township", "county": "Alcona"},
    {"name": "Gustin Township", "county": "Alcona"},
    {"name": "Harrisville Township", "county": "Alcona"},
    {"name": "Hawes Township", "county": "Alcona"},
    {"name": "Haynes Township", "county": "Alcona"},
    {"name": "Mikado Township", "county": "Alcona"},
    {"name": "Millen Township", "county": "Alcona"},
    {"name": "Mitchell Township", "county": "Alcona"},
    # Alger County (8)
    {"name": "Au Train Township", "county": "Alger"},
    {"name": "Burt Township", "county": "Alger"},
    {"name": "Grand Island Township", "county": "Alger"},
    {"name": "Limestone Township", "county": "Alger"},
    {"name": "Mathias Township", "county": "Alger"},
    {"name": "Munising Township", "county": "Alger"},
    {"name": "Onota Township", "county": "Alger"},
    {"name": "Rock River Township", "county": "Alger"},
    # Allegan County (22)
    {"name": "Allegan Township", "county": "Allegan"},
    {"name": "Casco Township", "county": "Allegan"},
    {"name": "Cheshire Township", "county": "Allegan"},
    {"name": "Clyde Township", "county": "Allegan"},
    {"name": "Dorr Township", "county": "Allegan"},
    {"name": "Fillmore Township", "county": "Allegan"},
    {"name": "Ganges Township", "county": "Allegan"},
    {"name": "Gun Plain Township", "county": "Allegan"},
    {"name": "Heath Township", "county": "Allegan"},
    {"name": "Hopkins Township", "county": "Allegan"},
    {"name": "Laketown Township", "county": "Allegan"},
    {"name": "Lee Township", "county": "Allegan"},
    {"name": "Leighton Township", "county": "Allegan"},
    {"name": "Manlius Township", "county": "Allegan"},
    {"name": "Martin Township", "county": "Allegan"},
    {"name": "Monterey Township", "county": "Allegan"},
    {"name": "Otsego Township", "county": "Allegan"},
    {"name": "Overisel Township", "county": "Allegan"},
    {"name": "Salem Township", "county": "Allegan"},
    {"name": "Saugatuck Township", "county": "Allegan"},
    {"name": "Trowbridge Township", "county": "Allegan"},
    {"name": "Valley Township", "county": "Allegan"},
    {"name": "Watson Township", "county": "Allegan"},
    {"name": "Wayland Township", "county": "Allegan"},
    # Alpena County (8)
    {"name": "Alpena Township", "county": "Alpena"},
    {"name": "Green Township", "county": "Alpena"},
    {"name": "Long Rapids Township", "county": "Alpena"},
    {"name": "Maple Ridge Township", "county": "Alpena"},
    {"name": "Ossineke Township", "county": "Alpena"},
    {"name": "Sanborn Township", "county": "Alpena"},
    {"name": "Wellington Township", "county": "Alpena"},
    {"name": "Wilson Township", "county": "Alpena"},
    # Antrim County (14)
    {"name": "Banks Township", "county": "Antrim"},
    {"name": "Central Lake Township", "county": "Antrim"},
    {"name": "Chestonia Township", "county": "Antrim"},
    {"name": "Custer Township", "county": "Antrim"},
    {"name": "Echo Township", "county": "Antrim"},
    {"name": "Elk Rapids Township", "county": "Antrim"},
    {"name": "Forest Home Township", "county": "Antrim"},
    {"name": "Helena Township", "county": "Antrim"},
    {"name": "Jordan Township", "county": "Antrim"},
    {"name": "Kearney Township", "county": "Antrim"},
    {"name": "Mancelona Township", "county": "Antrim"},
    {"name": "Milton Township", "county": "Antrim"},
    {"name": "Star Township", "county": "Antrim"},
    {"name": "Warner Township", "county": "Antrim"},
    # Arenac County (11)
    {"name": "Adams Township", "county": "Arenac"},
    {"name": "Arenac Township", "county": "Arenac"},
    {"name": "Au Gres Township", "county": "Arenac"},
    {"name": "Clayton Township", "county": "Arenac"},
    {"name": "Deep River Township", "county": "Arenac"},
    {"name": "Lincoln Township", "county": "Arenac"},
    {"name": "Mason Township", "county": "Arenac"},
    {"name": "Moffatt Township", "county": "Arenac"},
    {"name": "Standish Township", "county": "Arenac"},
    {"name": "Turner Township", "county": "Arenac"},
    {"name": "Whitney Township", "county": "Arenac"},
    # Baraga County (5)
    {"name": "Arvon Township", "county": "Baraga"},
    {"name": "Baraga Township", "county": "Baraga"},
    {"name": "Covington Township", "county": "Baraga"},
    {"name": "L'Anse Township", "county": "Baraga"},
    {"name": "Spurr Township", "county": "Baraga"},
    # Barry County (16)
    {"name": "Assyria Township", "county": "Barry"},
    {"name": "Baltimore Township", "county": "Barry"},
    {"name": "Barry Township", "county": "Barry"},
    {"name": "Carlton Township", "county": "Barry"},
    {"name": "Castleton Township", "county": "Barry"},
    {"name": "Hastings Township", "county": "Barry"},
    {"name": "Hope Township", "county": "Barry"},
    {"name": "Irving Township", "county": "Barry"},
    {"name": "Johnstown Township", "county": "Barry"},
    {"name": "Maple Grove Township", "county": "Barry"},
    {"name": "Orangeville Township", "county": "Barry"},
    {"name": "Prairieville Township", "county": "Barry"},
    {"name": "Rutland Township", "county": "Barry"},
    {"name": "Thornapple Township", "county": "Barry"},
    {"name": "Woodland Township", "county": "Barry"},
    {"name": "Yankee Springs Township", "county": "Barry"},
    # Bay County (14)
    {"name": "Bangor Township", "county": "Bay"},
    {"name": "Beaver Township", "county": "Bay"},
    {"name": "Frankenlust Township", "county": "Bay"},
    {"name": "Fraser Township", "county": "Bay"},
    {"name": "Garfield Township", "county": "Bay"},
    {"name": "Gibson Township", "county": "Bay"},
    {"name": "Hampton Township", "county": "Bay"},
    {"name": "Kawkawlin Township", "county": "Bay"},
    {"name": "Merritt Township", "county": "Bay"},
    {"name": "Monitor Township", "county": "Bay"},
    {"name": "Mount Forest Township", "county": "Bay"},
    {"name": "Pinconning Township", "county": "Bay"},
    {"name": "Portsmouth Township", "county": "Bay"},
    {"name": "Williams Township", "county": "Bay"},
    # Benzie County (11)
    {"name": "Almira Township", "county": "Benzie"},
    {"name": "Benzonia Township", "county": "Benzie"},
    {"name": "Blaine Township", "county": "Benzie"},
    {"name": "Colfax Township", "county": "Benzie"},
    {"name": "Crystal Lake Township", "county": "Benzie"},
    {"name": "Homestead Township", "county": "Benzie"},
    {"name": "Inland Township", "county": "Benzie"},
    {"name": "Joyfield Township", "county": "Benzie"},
    {"name": "Lake Township", "county": "Benzie"},
    {"name": "Platte Township", "county": "Benzie"},
    {"name": "Weldon Township", "county": "Benzie"},
    # Berrien County (22)
    {"name": "Bainbridge Township", "county": "Berrien"},
    {"name": "Baroda Township", "county": "Berrien"},
    {"name": "Benton Township", "county": "Berrien"},
    {"name": "Berrien Township", "county": "Berrien"},
    {"name": "Bertrand Township", "county": "Berrien"},
    {"name": "Buchanan Township", "county": "Berrien"},
    {"name": "Chikaming Township", "county": "Berrien"},
    {"name": "Coloma Township", "county": "Berrien"},
    {"name": "Galien Township", "county": "Berrien"},
    {"name": "Hagar Township", "county": "Berrien"},
    {"name": "Lake Township", "county": "Berrien"},
    {"name": "Lincoln Township", "county": "Berrien"},
    {"name": "New Buffalo Township", "county": "Berrien"},
    {"name": "Niles Township", "county": "Berrien"},
    {"name": "Oronoko Township", "county": "Berrien"},
    {"name": "Pipestone Township", "county": "Berrien"},
    {"name": "Royalton Township", "county": "Berrien"},
    {"name": "Sodus Township", "county": "Berrien"},
    {"name": "St. Joseph Township", "county": "Berrien"},
    {"name": "Three Oaks Township", "county": "Berrien"},
    {"name": "Watervliet Township", "county": "Berrien"},
    {"name": "Weesaw Township", "county": "Berrien"},
    # Branch County (16)
    {"name": "Algansee Township", "county": "Branch"},
    {"name": "Batavia Township", "county": "Branch"},
    {"name": "Bethel Township", "county": "Branch"},
    {"name": "Bronson Township", "county": "Branch"},
    {"name": "Butler Township", "county": "Branch"},
    {"name": "California Township", "county": "Branch"},
    {"name": "Coldwater Township", "county": "Branch"},
    {"name": "Gilead Township", "county": "Branch"},
    {"name": "Girard Township", "county": "Branch"},
    {"name": "Kinderhook Township", "county": "Branch"},
    {"name": "Matteson Township", "county": "Branch"},
    {"name": "Noble Township", "county": "Branch"},
    {"name": "Ovid Township", "county": "Branch"},
    {"name": "Quincy Township", "county": "Branch"},
    {"name": "Sherwood Township", "county": "Branch"},
    {"name": "Union Township", "county": "Branch"},
    # Calhoun County (18)
    {"name": "Albion Township", "county": "Calhoun"},
    {"name": "Athens Township", "county": "Calhoun"},
    {"name": "Bedford Township", "county": "Calhoun"},
    {"name": "Burlington Township", "county": "Calhoun"},
    {"name": "Clarence Township", "county": "Calhoun"},
    {"name": "Clarendon Township", "county": "Calhoun"},
    {"name": "Convis Township", "county": "Calhoun"},
    {"name": "Eckford Township", "county": "Calhoun"},
    {"name": "Emmett Township", "county": "Calhoun"},
    {"name": "Fredonia Township", "county": "Calhoun"},
    {"name": "Homer Township", "county": "Calhoun"},
    {"name": "Lee Township", "county": "Calhoun"},
    {"name": "Leroy Township", "county": "Calhoun"},
    {"name": "Marengo Township", "county": "Calhoun"},
    {"name": "Marshall Township", "county": "Calhoun"},
    {"name": "Newton Township", "county": "Calhoun"},
    {"name": "Pennfield Township", "county": "Calhoun"},
    {"name": "Sheridan Township", "county": "Calhoun"},
    # Cass County (16)
    {"name": "Calvin Township", "county": "Cass"},
    {"name": "Howard Township", "county": "Cass"},
    {"name": "Jefferson Township", "county": "Cass"},
    {"name": "LaGrange Township", "county": "Cass"},
    {"name": "Marcellus Township", "county": "Cass"},
    {"name": "Mason Township", "county": "Cass"},
    {"name": "Milton Township", "county": "Cass"},
    {"name": "Newberg Township", "county": "Cass"},
    {"name": "Ontwa Township", "county": "Cass"},
    {"name": "Penn Township", "county": "Cass"},
    {"name": "Pokagon Township", "county": "Cass"},
    {"name": "Porter Township", "county": "Cass"},
    {"name": "Silver Creek Township", "county": "Cass"},
    {"name": "Volinia Township", "county": "Cass"},
    {"name": "Wayne Township", "county": "Cass"},
    # Charlevoix County (13)
    {"name": "Bay Township", "county": "Charlevoix"},
    {"name": "Boyne Valley Township", "county": "Charlevoix"},
    {"name": "Chandler Township", "county": "Charlevoix"},
    {"name": "Charlevoix Township", "county": "Charlevoix"},
    {"name": "Evangeline Township", "county": "Charlevoix"},
    {"name": "Eveline Township", "county": "Charlevoix"},
    {"name": "Hayes Township", "county": "Charlevoix"},
    {"name": "Hudson Township", "county": "Charlevoix"},
    {"name": "Marion Township", "county": "Charlevoix"},
    {"name": "Melrose Township", "county": "Charlevoix"},
    {"name": "Norwood Township", "county": "Charlevoix"},
    {"name": "South Arm Township", "county": "Charlevoix"},
    {"name": "Wilson Township", "county": "Charlevoix"},
    # Cheboygan County (19)
    {"name": "Aloha Township", "county": "Cheboygan"},
    {"name": "Beaugrand Township", "county": "Cheboygan"},
    {"name": "Benton Township", "county": "Cheboygan"},
    {"name": "Burt Township", "county": "Cheboygan"},
    {"name": "Ellis Township", "county": "Cheboygan"},
    {"name": "Forest Township", "county": "Cheboygan"},
    {"name": "Grant Township", "county": "Cheboygan"},
    {"name": "Hebron Township", "county": "Cheboygan"},
    {"name": "Inverness Township", "county": "Cheboygan"},
    {"name": "Koehler Township", "county": "Cheboygan"},
    {"name": "Mackinaw Township", "county": "Cheboygan"},
    {"name": "Mentor Township", "county": "Cheboygan"},
    {"name": "Mullett Township", "county": "Cheboygan"},
    {"name": "Munro Township", "county": "Cheboygan"},
    {"name": "Nunda Township", "county": "Cheboygan"},
    {"name": "Tuscarora Township", "county": "Cheboygan"},
    {"name": "Walker Township", "county": "Cheboygan"},
    {"name": "Waverly Township", "county": "Cheboygan"},
    {"name": "Wilmot Township", "county": "Cheboygan"},
    # Chippewa County (16)
    {"name": "Bay Mills Township", "county": "Chippewa"},
    {"name": "Bruce Township", "county": "Chippewa"},
    {"name": "Chippewa Township", "county": "Chippewa"},
    {"name": "Dafter Township", "county": "Chippewa"},
    {"name": "DeTour Township", "county": "Chippewa"},
    {"name": "Drummond Township", "county": "Chippewa"},
    {"name": "Hulbert Township", "county": "Chippewa"},
    {"name": "Kinross Township", "county": "Chippewa"},
    {"name": "Pickford Township", "county": "Chippewa"},
    {"name": "Raber Township", "county": "Chippewa"},
    {"name": "Rudyard Township", "county": "Chippewa"},
    {"name": "Soo Township", "county": "Chippewa"},
    {"name": "Sugar Island Township", "county": "Chippewa"},
    {"name": "Superior Township", "county": "Chippewa"},
    {"name": "Trout Lake Township", "county": "Chippewa"},
    {"name": "Whitefish Township", "county": "Chippewa"},
    # Clare County (15)
    {"name": "Arthur Township", "county": "Clare"},
    {"name": "Franklin Township", "county": "Clare"},
    {"name": "Freeman Township", "county": "Clare"},
    {"name": "Frost Township", "county": "Clare"},
    {"name": "Garfield Township", "county": "Clare"},
    {"name": "Grant Township", "county": "Clare"},
    {"name": "Greenwood Township", "county": "Clare"},
    {"name": "Hamilton Township", "county": "Clare"},
    {"name": "Hatton Township", "county": "Clare"},
    {"name": "Hayes Township", "county": "Clare"},
    {"name": "Lincoln Township", "county": "Clare"},
    {"name": "Redding Township", "county": "Clare"},
    {"name": "Sheridan Township", "county": "Clare"},
    {"name": "Summerfield Township", "county": "Clare"},
    {"name": "Surrey Township", "county": "Clare"},
    {"name": "Winterfield Township", "county": "Clare"},
    # Clinton County (16)
    {"name": "Bath Township", "county": "Clinton"},
    {"name": "Bengal Township", "county": "Clinton"},
    {"name": "Bingham Township", "county": "Clinton"},
    {"name": "Dallas Township", "county": "Clinton"},
    {"name": "DeWitt Township", "county": "Clinton"},
    {"name": "Duplain Township", "county": "Clinton"},
    {"name": "Eagle Township", "county": "Clinton"},
    {"name": "Essex Township", "county": "Clinton"},
    {"name": "Greenbush Township", "county": "Clinton"},
    {"name": "Lebanon Township", "county": "Clinton"},
    {"name": "Olive Township", "county": "Clinton"},
    {"name": "Ovid Township", "county": "Clinton"},
    {"name": "Riley Township", "county": "Clinton"},
    {"name": "Victor Township", "county": "Clinton"},
    {"name": "Watertown Township", "county": "Clinton"},
    {"name": "Westphalia Township", "county": "Clinton"},
    # Crawford County (6)
    {"name": "Beaver Creek Township", "county": "Crawford"},
    {"name": "Frederic Township", "county": "Crawford"},
    {"name": "Grayling Township", "county": "Crawford"},
    {"name": "Lovells Township", "county": "Crawford"},
    {"name": "Maple Forest Township", "county": "Crawford"},
    {"name": "South Branch Township", "county": "Crawford"},
    # Delta County (13)
    {"name": "Baldwin Township", "county": "Delta"},
    {"name": "Bay de Noc Township", "county": "Delta"},
    {"name": "Brampton Township", "county": "Delta"},
    {"name": "Cornell Township", "county": "Delta"},
    {"name": "Ensign Township", "county": "Delta"},
    {"name": "Escanaba Township", "county": "Delta"},
    {"name": "Fairbanks Township", "county": "Delta"},
    {"name": "Ford River Township", "county": "Delta"},
    {"name": "Garden Township", "county": "Delta"},
    {"name": "Maple Ridge Township", "county": "Delta"},
    {"name": "Masonville Township", "county": "Delta"},
    {"name": "Nahma Township", "county": "Delta"},
    {"name": "Wells Township", "county": "Delta"},
    # Dickinson County (7)
    {"name": "Breen Township", "county": "Dickinson"},
    {"name": "Breitung Township", "county": "Dickinson"},
    {"name": "Felch Township", "county": "Dickinson"},
    {"name": "Norway Township", "county": "Dickinson"},
    {"name": "Sagola Township", "county": "Dickinson"},
    {"name": "Waucedah Township", "county": "Dickinson"},
    {"name": "West Branch Township", "county": "Dickinson"},
    # Eaton County (15)
    {"name": "Bellevue Township", "county": "Eaton"},
    {"name": "Benton Township", "county": "Eaton"},
    {"name": "Brookfield Township", "county": "Eaton"},
    {"name": "Carmel Township", "county": "Eaton"},
    {"name": "Delta Township", "county": "Eaton"},
    {"name": "Eaton Township", "county": "Eaton"},
    {"name": "Eaton Rapids Township", "county": "Eaton"},
    {"name": "Hamlin Township", "county": "Eaton"},
    {"name": "Kalamo Township", "county": "Eaton"},
    {"name": "Oneida Township", "county": "Eaton"},
    {"name": "Roxand Township", "county": "Eaton"},
    {"name": "Sunfield Township", "county": "Eaton"},
    {"name": "Vermontville Township", "county": "Eaton"},
    {"name": "Walton Township", "county": "Eaton"},
    {"name": "Windsor Township", "county": "Eaton"},
    # Emmet County (15)
    {"name": "Bear Creek Township", "county": "Emmet"},
    {"name": "Bliss Township", "county": "Emmet"},
    {"name": "Carp Lake Township", "county": "Emmet"},
    {"name": "Center Township", "county": "Emmet"},
    {"name": "Friendship Township", "county": "Emmet"},
    {"name": "Little Traverse Township", "county": "Emmet"},
    {"name": "Littlefield Township", "county": "Emmet"},
    {"name": "Maple River Township", "county": "Emmet"},
    {"name": "McKinley Township", "county": "Emmet"},
    {"name": "Pleasantview Township", "county": "Emmet"},
    {"name": "Readmond Township", "county": "Emmet"},
    {"name": "Resort Township", "county": "Emmet"},
    {"name": "Springvale Township", "county": "Emmet"},
    {"name": "Wawatam Township", "county": "Emmet"},
    {"name": "West Traverse Township", "county": "Emmet"},
    # Genesee County (17)
    {"name": "Argentine Township", "county": "Genesee"},
    {"name": "Atlas Township", "county": "Genesee"},
    {"name": "Clayton Township", "county": "Genesee"},
    {"name": "Davison Township", "county": "Genesee"},
    {"name": "Fenton Township", "county": "Genesee"},
    {"name": "Flint Township", "county": "Genesee"},
    {"name": "Flushing Township", "county": "Genesee"},
    {"name": "Forest Township", "county": "Genesee"},
    {"name": "Gaines Township", "county": "Genesee"},
    {"name": "Genesee Township", "county": "Genesee"},
    {"name": "Grand Blanc Township", "county": "Genesee"},
    {"name": "Montrose Township", "county": "Genesee"},
    {"name": "Mount Morris Township", "county": "Genesee"},
    {"name": "Mundy Township", "county": "Genesee"},
    {"name": "Richfield Township", "county": "Genesee"},
    {"name": "Thetford Township", "county": "Genesee"},
    {"name": "Vienna Township", "county": "Genesee"},
    # Gladwin County (15)
    {"name": "Beaverton Township", "county": "Gladwin"},
    {"name": "Bentley Township", "county": "Gladwin"},
    {"name": "Billings Township", "county": "Gladwin"},
    {"name": "Bourret Township", "county": "Gladwin"},
    {"name": "Buckeye Township", "county": "Gladwin"},
    {"name": "Butman Township", "county": "Gladwin"},
    {"name": "Clement Township", "county": "Gladwin"},
    {"name": "Gladwin Township", "county": "Gladwin"},
    {"name": "Grout Township", "county": "Gladwin"},
    {"name": "Hay Township", "county": "Gladwin"},
    {"name": "Sage Township", "county": "Gladwin"},
    {"name": "Secord Township", "county": "Gladwin"},
    {"name": "Sherman Township", "county": "Gladwin"},
    {"name": "Tobacco Township", "county": "Gladwin"},
    # Gogebic County (5)
    {"name": "Bessemer Township", "county": "Gogebic"},
    {"name": "Erwin Township", "county": "Gogebic"},
    {"name": "Ironwood Township", "county": "Gogebic"},
    {"name": "Marenisco Township", "county": "Gogebic"},
    {"name": "Wakefield Township", "county": "Gogebic"},
    # Grand Traverse County (13)
    {"name": "Acme Township", "county": "Grand Traverse"},
    {"name": "Blair Township", "county": "Grand Traverse"},
    {"name": "East Bay Township", "county": "Grand Traverse"},
    {"name": "Fife Lake Township", "county": "Grand Traverse"},
    {"name": "Garfield Township", "county": "Grand Traverse"},
    {"name": "Grant Township", "county": "Grand Traverse"},
    {"name": "Green Lake Township", "county": "Grand Traverse"},
    {"name": "Long Lake Township", "county": "Grand Traverse"},
    {"name": "Mayfield Township", "county": "Grand Traverse"},
    {"name": "Paradise Township", "county": "Grand Traverse"},
    {"name": "Peninsula Township", "county": "Grand Traverse"},
    {"name": "Union Township", "county": "Grand Traverse"},
    {"name": "Whitewater Township", "county": "Grand Traverse"},
    # Gratiot County (16)
    {"name": "Arcada Township", "county": "Gratiot"},
    {"name": "Bethany Township", "county": "Gratiot"},
    {"name": "Elba Township", "county": "Gratiot"},
    {"name": "Emerson Township", "county": "Gratiot"},
    {"name": "Fulton Township", "county": "Gratiot"},
    {"name": "Hamilton Township", "county": "Gratiot"},
    {"name": "Lafayette Township", "county": "Gratiot"},
    {"name": "New Haven Township", "county": "Gratiot"},
    {"name": "Newark Township", "county": "Gratiot"},
    {"name": "North Shade Township", "county": "Gratiot"},
    {"name": "North Star Township", "county": "Gratiot"},
    {"name": "Pine River Township", "county": "Gratiot"},
    {"name": "Seville Township", "county": "Gratiot"},
    {"name": "Sumner Township", "county": "Gratiot"},
    {"name": "Washington Township", "county": "Gratiot"},
    {"name": "Wheeler Township", "county": "Gratiot"},
    # Hillsdale County (17)
    {"name": "Adams Township", "county": "Hillsdale"},
    {"name": "Allen Township", "county": "Hillsdale"},
    {"name": "Amboy Township", "county": "Hillsdale"},
    {"name": "Cambria Township", "county": "Hillsdale"},
    {"name": "Camden Township", "county": "Hillsdale"},
    {"name": "Fayette Township", "county": "Hillsdale"},
    {"name": "Hillsdale Township", "county": "Hillsdale"},
    {"name": "Jefferson Township", "county": "Hillsdale"},
    {"name": "Moscow Township", "county": "Hillsdale"},
    {"name": "Pittsford Township", "county": "Hillsdale"},
    {"name": "Ransom Township", "county": "Hillsdale"},
    {"name": "Reading Township", "county": "Hillsdale"},
    {"name": "Scipio Township", "county": "Hillsdale"},
    {"name": "Somerset Township", "county": "Hillsdale"},
    {"name": "Wheatland Township", "county": "Hillsdale"},
    {"name": "Woodbridge Township", "county": "Hillsdale"},
    {"name": "Wright Township", "county": "Hillsdale"},
    # Houghton County (14)
    {"name": "Adams Township", "county": "Houghton"},
    {"name": "Calumet Township", "county": "Houghton"},
    {"name": "Chassell Township", "county": "Houghton"},
    {"name": "Duncan Township", "county": "Houghton"},
    {"name": "Elm River Township", "county": "Houghton"},
    {"name": "Franklin Township", "county": "Houghton"},
    {"name": "Hancock Township", "county": "Houghton"},
    {"name": "Laird Township", "county": "Houghton"},
    {"name": "Osceola Township", "county": "Houghton"},
    {"name": "Portage Township", "county": "Houghton"},
    {"name": "Quincy Township", "county": "Houghton"},
    {"name": "Schoolcraft Township", "county": "Houghton"},
    {"name": "Stanton Township", "county": "Houghton"},
    {"name": "Torch Lake Township", "county": "Houghton"},
    # Huron County (27)
    {"name": "Bingham Township", "county": "Huron"},
    {"name": "Bloomfield Township", "county": "Huron"},
    {"name": "Brookfield Township", "county": "Huron"},
    {"name": "Caseville Township", "county": "Huron"},
    {"name": "Chandler Township", "county": "Huron"},
    {"name": "Colfax Township", "county": "Huron"},
    {"name": "Dwight Township", "county": "Huron"},
    {"name": "Fair Haven Township", "county": "Huron"},
    {"name": "Gore Township", "county": "Huron"},
    {"name": "Grant Township", "county": "Huron"},
    {"name": "Hume Township", "county": "Huron"},
    {"name": "Huron Township", "county": "Huron"},
    {"name": "Lake Township", "county": "Huron"},
    {"name": "Lincoln Township", "county": "Huron"},
    {"name": "McKinley Township", "county": "Huron"},
    {"name": "Meade Township", "county": "Huron"},
    {"name": "Oliver Township", "county": "Huron"},
    {"name": "Paris Township", "county": "Huron"},
    {"name": "Pointe Aux Barques Township", "county": "Huron"},
    {"name": "Port Austin Township", "county": "Huron"},
    {"name": "Rubicon Township", "county": "Huron"},
    {"name": "Sand Beach Township", "county": "Huron"},
    {"name": "Sebewaing Township", "county": "Huron"},
    {"name": "Sheridan Township", "county": "Huron"},
    {"name": "Sherman Township", "county": "Huron"},
    {"name": "Sigel Township", "county": "Huron"},
    {"name": "Verona Township", "county": "Huron"},
    {"name": "Winsor Township", "county": "Huron"},
    # Ingham County (16)
    {"name": "Alaiedon Township", "county": "Ingham"},
    {"name": "Aurelius Township", "county": "Ingham"},
    {"name": "Bunker Hill Township", "county": "Ingham"},
    {"name": "Delhi Township", "county": "Ingham"},
    {"name": "Ingham Township", "county": "Ingham"},
    {"name": "Lansing Township", "county": "Ingham"},
    {"name": "Leroy Township", "county": "Ingham"},
    {"name": "Leslie Township", "county": "Ingham"},
    {"name": "Locke Township", "county": "Ingham"},
    {"name": "Meridian Township", "county": "Ingham"},
    {"name": "Onondaga Township", "county": "Ingham"},
    {"name": "Stockbridge Township", "county": "Ingham"},
    {"name": "Vevay Township", "county": "Ingham"},
    {"name": "Wheatfield Township", "county": "Ingham"},
    {"name": "White Oak Township", "county": "Ingham"},
    {"name": "Williamston Township", "county": "Ingham"},
    # Ionia County (16)
    {"name": "Berlin Township", "county": "Ionia"},
    {"name": "Boston Township", "county": "Ionia"},
    {"name": "Campbell Township", "county": "Ionia"},
    {"name": "Danby Township", "county": "Ionia"},
    {"name": "Easton Township", "county": "Ionia"},
    {"name": "Ionia Township", "county": "Ionia"},
    {"name": "Keene Township", "county": "Ionia"},
    {"name": "Lyons Township", "county": "Ionia"},
    {"name": "North Plains Township", "county": "Ionia"},
    {"name": "Odessa Township", "county": "Ionia"},
    {"name": "Orange Township", "county": "Ionia"},
    {"name": "Orleans Township", "county": "Ionia"},
    {"name": "Otisco Township", "county": "Ionia"},
    {"name": "Portland Township", "county": "Ionia"},
    {"name": "Ronald Township", "county": "Ionia"},
    {"name": "Sebewa Township", "county": "Ionia"},
    # Iosco County (11)
    {"name": "Alabaster Township", "county": "Iosco"},
    {"name": "AuSable Township", "county": "Iosco"},
    {"name": "Baldwin Township", "county": "Iosco"},
    {"name": "Burleigh Township", "county": "Iosco"},
    {"name": "Grant Township", "county": "Iosco"},
    {"name": "Oscoda Township", "county": "Iosco"},
    {"name": "Plainfield Township", "county": "Iosco"},
    {"name": "Reno Township", "county": "Iosco"},
    {"name": "Sherman Township", "county": "Iosco"},
    {"name": "Tawas Township", "county": "Iosco"},
    {"name": "Wilber Township", "county": "Iosco"},
    # Iron County (7)
    {"name": "Bates Township", "county": "Iron"},
    {"name": "Crystal Falls Township", "county": "Iron"},
    {"name": "Hematite Township", "county": "Iron"},
    {"name": "Iron River Township", "county": "Iron"},
    {"name": "Mansfield Township", "county": "Iron"},
    {"name": "Mastodon Township", "county": "Iron"},
    {"name": "Stambaugh Township", "county": "Iron"},
    # Isabella County (16)
    {"name": "Broomfield Township", "county": "Isabella"},
    {"name": "Chippewa Township", "county": "Isabella"},
    {"name": "Coe Township", "county": "Isabella"},
    {"name": "Coldwater Township", "county": "Isabella"},
    {"name": "Deerfield Township", "county": "Isabella"},
    {"name": "Denver Township", "county": "Isabella"},
    {"name": "Fremont Township", "county": "Isabella"},
    {"name": "Gilmore Township", "county": "Isabella"},
    {"name": "Isabella Township", "county": "Isabella"},
    {"name": "Lincoln Township", "county": "Isabella"},
    {"name": "Nottawa Township", "county": "Isabella"},
    {"name": "Rolland Township", "county": "Isabella"},
    {"name": "Sherman Township", "county": "Isabella"},
    {"name": "Union Township", "county": "Isabella"},
    {"name": "Vernon Township", "county": "Isabella"},
    {"name": "Wise Township", "county": "Isabella"},
    # Jackson County (19)
    {"name": "Blackman Township", "county": "Jackson"},
    {"name": "Columbia Township", "county": "Jackson"},
    {"name": "Concord Township", "county": "Jackson"},
    {"name": "Grass Lake Township", "county": "Jackson"},
    {"name": "Hanover Township", "county": "Jackson"},
    {"name": "Henrietta Township", "county": "Jackson"},
    {"name": "Leoni Township", "county": "Jackson"},
    {"name": "Liberty Township", "county": "Jackson"},
    {"name": "Napoleon Township", "county": "Jackson"},
    {"name": "Norvell Township", "county": "Jackson"},
    {"name": "Parma Township", "county": "Jackson"},
    {"name": "Pulaski Township", "county": "Jackson"},
    {"name": "Rives Township", "county": "Jackson"},
    {"name": "Sandstone Township", "county": "Jackson"},
    {"name": "Spring Arbor Township", "county": "Jackson"},
    {"name": "Springport Township", "county": "Jackson"},
    {"name": "Summit Township", "county": "Jackson"},
    {"name": "Tompkins Township", "county": "Jackson"},
    {"name": "Waterloo Township", "county": "Jackson"},
    # Kalamazoo County (15)
    {"name": "Alamo Township", "county": "Kalamazoo"},
    {"name": "Brady Township", "county": "Kalamazoo"},
    {"name": "Charleston Township", "county": "Kalamazoo"},
    {"name": "Climax Township", "county": "Kalamazoo"},
    {"name": "Comstock Township", "county": "Kalamazoo"},
    {"name": "Cooper Township", "county": "Kalamazoo"},
    {"name": "Kalamazoo Township", "county": "Kalamazoo"},
    {"name": "Oshtemo Township", "county": "Kalamazoo"},
    {"name": "Pavilion Township", "county": "Kalamazoo"},
    {"name": "Prairie Ronde Township", "county": "Kalamazoo"},
    {"name": "Richland Township", "county": "Kalamazoo"},
    {"name": "Ross Township", "county": "Kalamazoo"},
    {"name": "Schoolcraft Township", "county": "Kalamazoo"},
    {"name": "Texas Township", "county": "Kalamazoo"},
    {"name": "Wakeshma Township", "county": "Kalamazoo"},
    # Kalkaska County (12)
    {"name": "Bear Lake Township", "county": "Kalkaska"},
    {"name": "Blue Lake Township", "county": "Kalkaska"},
    {"name": "Boardman Township", "county": "Kalkaska"},
    {"name": "Clearwater Township", "county": "Kalkaska"},
    {"name": "Cold Springs Township", "county": "Kalkaska"},
    {"name": "Excelsior Township", "county": "Kalkaska"},
    {"name": "Garfield Township", "county": "Kalkaska"},
    {"name": "Kalkaska Township", "county": "Kalkaska"},
    {"name": "Oliver Township", "county": "Kalkaska"},
    {"name": "Orange Township", "county": "Kalkaska"},
    {"name": "Rapid River Township", "county": "Kalkaska"},
    {"name": "Springfield Township", "county": "Kalkaska"},
    # Kent County (19)
    {"name": "Ada Township", "county": "Kent"},
    {"name": "Algoma Township", "county": "Kent"},
    {"name": "Alpine Township", "county": "Kent"},
    {"name": "Bowne Township", "county": "Kent"},
    {"name": "Byron Township", "county": "Kent"},
    {"name": "Caledonia Township", "county": "Kent"},
    {"name": "Cannon Township", "county": "Kent"},
    {"name": "Cascade Township", "county": "Kent"},
    {"name": "Courtland Township", "county": "Kent"},
    {"name": "Gaines Township", "county": "Kent"},
    {"name": "Grattan Township", "county": "Kent"},
    {"name": "Lowell Township", "county": "Kent"},
    {"name": "Nelson Township", "county": "Kent"},
    {"name": "Oakfield Township", "county": "Kent"},
    {"name": "Solon Township", "county": "Kent"},
    {"name": "Sparta Township", "county": "Kent"},
    {"name": "Spencer Township", "county": "Kent"},
    {"name": "Tyrone Township", "county": "Kent"},
    {"name": "Vergennes Township", "county": "Kent"},
    # Keweenaw County (5)
    {"name": "Allouez Township", "county": "Keweenaw"},
    {"name": "Eagle Harbor Township", "county": "Keweenaw"},
    {"name": "Grant Township", "county": "Keweenaw"},
    {"name": "Houghton Township", "county": "Keweenaw"},
    {"name": "Sherman Township", "county": "Keweenaw"},
    # Lake County (15)
    {"name": "Chase Township", "county": "Lake"},
    {"name": "Cherry Valley Township", "county": "Lake"},
    {"name": "Dover Township", "county": "Lake"},
    {"name": "Eden Township", "county": "Lake"},
    {"name": "Elk Township", "county": "Lake"},
    {"name": "Ellsworth Township", "county": "Lake"},
    {"name": "Lake Township", "county": "Lake"},
    {"name": "Newkirk Township", "county": "Lake"},
    {"name": "Peacock Township", "county": "Lake"},
    {"name": "Pinora Township", "county": "Lake"},
    {"name": "Pleasant Plains Township", "county": "Lake"},
    {"name": "Sauble Township", "county": "Lake"},
    {"name": "Sweetwater Township", "county": "Lake"},
    {"name": "Webber Township", "county": "Lake"},
    {"name": "Yates Township", "county": "Lake"},
    # Lapeer County (17)
    {"name": "Almont Township", "county": "Lapeer"},
    {"name": "Arcadia Township", "county": "Lapeer"},
    {"name": "Attica Township", "county": "Lapeer"},
    {"name": "Burlington Township", "county": "Lapeer"},
    {"name": "Burnside Township", "county": "Lapeer"},
    {"name": "Deerfield Township", "county": "Lapeer"},
    {"name": "Dryden Township", "county": "Lapeer"},
    {"name": "Elba Township", "county": "Lapeer"},
    {"name": "Goodland Township", "county": "Lapeer"},
    {"name": "Hadley Township", "county": "Lapeer"},
    {"name": "Imlay Township", "county": "Lapeer"},
    {"name": "Lapeer Township", "county": "Lapeer"},
    {"name": "Marathon Township", "county": "Lapeer"},
    {"name": "Metamora Township", "county": "Lapeer"},
    {"name": "North Branch Township", "county": "Lapeer"},
    {"name": "Oregon Township", "county": "Lapeer"},
    {"name": "Rich Township", "county": "Lapeer"},
    # Leelanau County (11)
    {"name": "Bingham Township", "county": "Leelanau"},
    {"name": "Centerville Township", "county": "Leelanau"},
    {"name": "Cleveland Township", "county": "Leelanau"},
    {"name": "Elmwood Township", "county": "Leelanau"},
    {"name": "Empire Township", "county": "Leelanau"},
    {"name": "Glen Arbor Township", "county": "Leelanau"},
    {"name": "Kasson Township", "county": "Leelanau"},
    {"name": "Leelanau Township", "county": "Leelanau"},
    {"name": "Leland Township", "county": "Leelanau"},
    {"name": "Solon Township", "county": "Leelanau"},
    {"name": "Suttons Bay Township", "county": "Leelanau"},
    # Lenawee County (23)
    {"name": "Adrian Township", "county": "Lenawee"},
    {"name": "Blissfield Township", "county": "Lenawee"},
    {"name": "Cambridge Township", "county": "Lenawee"},
    {"name": "Clinton Township", "county": "Lenawee"},
    {"name": "Deerfield Township", "county": "Lenawee"},
    {"name": "Dover Township", "county": "Lenawee"},
    {"name": "Fairfield Township", "county": "Lenawee"},
    {"name": "Franklin Township", "county": "Lenawee"},
    {"name": "Hudson Township", "county": "Lenawee"},
    {"name": "Macon Township", "county": "Lenawee"},
    {"name": "Madison Township", "county": "Lenawee"},
    {"name": "Medina Township", "county": "Lenawee"},
    {"name": "Ogden Township", "county": "Lenawee"},
    {"name": "Palmyra Township", "county": "Lenawee"},
    {"name": "Raisin Township", "county": "Lenawee"},
    {"name": "Ridgeway Township", "county": "Lenawee"},
    {"name": "Riga Township", "county": "Lenawee"},
    {"name": "Rollin Township", "county": "Lenawee"},
    {"name": "Rome Township", "county": "Lenawee"},
    {"name": "Seneca Township", "county": "Lenawee"},
    {"name": "Tecumseh Township", "county": "Lenawee"},
    {"name": "Woodstock Township", "county": "Lenawee"},
    # Livingston County (15)
    {"name": "Brighton Township", "county": "Livingston"},
    {"name": "Cohoctah Township", "county": "Livingston"},
    {"name": "Conway Township", "county": "Livingston"},
    {"name": "Deerfield Township", "county": "Livingston"},
    {"name": "Genoa Township", "county": "Livingston"},
    {"name": "Green Oak Township", "county": "Livingston"},
    {"name": "Hamburg Township", "county": "Livingston"},
    {"name": "Handy Township", "county": "Livingston"},
    {"name": "Hartland Township", "county": "Livingston"},
    {"name": "Howell Township", "county": "Livingston"},
    {"name": "Iosco Township", "county": "Livingston"},
    {"name": "Marion Township", "county": "Livingston"},
    {"name": "Oceola Township", "county": "Livingston"},
    {"name": "Putnam Township", "county": "Livingston"},
    {"name": "Tyrone Township", "county": "Livingston"},
    {"name": "Unadilla Township", "county": "Livingston"},
    # Luce County (4)
    {"name": "Columbus Township", "county": "Luce"},
    {"name": "Lakefield Township", "county": "Luce"},
    {"name": "McMillan Township", "county": "Luce"},
    {"name": "Pentland Township", "county": "Luce"},
    # Mackinac County (10)
    {"name": "Bois Blanc Township", "county": "Mackinac"},
    {"name": "Brevort Township", "county": "Mackinac"},
    {"name": "Clark Township", "county": "Mackinac"},
    {"name": "Garfield Township", "county": "Mackinac"},
    {"name": "Hendricks Township", "county": "Mackinac"},
    {"name": "Marquette Township", "county": "Mackinac"},
    {"name": "Moran Township", "county": "Mackinac"},
    {"name": "Newton Township", "county": "Mackinac"},
    {"name": "Portage Township", "county": "Mackinac"},
    {"name": "St. Ignace Township", "county": "Mackinac"},
    # Macomb County (12)
    {"name": "Armada Township", "county": "Macomb"},
    {"name": "Bruce Township", "county": "Macomb"},
    {"name": "Chesterfield Township", "county": "Macomb"},
    {"name": "Clinton Township", "county": "Macomb"},
    {"name": "Harrison Township", "county": "Macomb"},
    {"name": "Lake Township", "county": "Macomb"},
    {"name": "Lenox Township", "county": "Macomb"},
    {"name": "Macomb Township", "county": "Macomb"},
    {"name": "Ray Township", "county": "Macomb"},
    {"name": "Richmond Township", "county": "Macomb"},
    {"name": "Shelby Township", "county": "Macomb"},
    {"name": "Washington Township", "county": "Macomb"},
    # Manistee County (14)
    {"name": "Arcadia Township", "county": "Manistee"},
    {"name": "Bear Lake Township", "county": "Manistee"},
    {"name": "Brown Township", "county": "Manistee"},
    {"name": "Cleon Township", "county": "Manistee"},
    {"name": "Dickson Township", "county": "Manistee"},
    {"name": "Filer Township", "county": "Manistee"},
    {"name": "Manistee Township", "county": "Manistee"},
    {"name": "Maple Grove Township", "county": "Manistee"},
    {"name": "Marilla Township", "county": "Manistee"},
    {"name": "Norman Township", "county": "Manistee"},
    {"name": "Onekama Township", "county": "Manistee"},
    {"name": "Pleasanton Township", "county": "Manistee"},
    {"name": "Springdale Township", "county": "Manistee"},
    {"name": "Stronach Township", "county": "Manistee"},
    # Marquette County (18)
    {"name": "Champion Township", "county": "Marquette"},
    {"name": "Chocolay Township", "county": "Marquette"},
    {"name": "Ely Township", "county": "Marquette"},
    {"name": "Ewing Township", "county": "Marquette"},
    {"name": "Forsyth Township", "county": "Marquette"},
    {"name": "Humboldt Township", "county": "Marquette"},
    {"name": "Ishpeming Township", "county": "Marquette"},
    {"name": "Michigamme Township", "county": "Marquette"},
    {"name": "Negaunee Township", "county": "Marquette"},
    {"name": "Powell Township", "county": "Marquette"},
    {"name": "Republic Township", "county": "Marquette"},
    {"name": "Richmond Township", "county": "Marquette"},
    {"name": "Sands Township", "county": "Marquette"},
    {"name": "Skandia Township", "county": "Marquette"},
    {"name": "Tilden Township", "county": "Marquette"},
    {"name": "Turin Township", "county": "Marquette"},
    {"name": "Wells Township", "county": "Marquette"},
    {"name": "West Branch Township", "county": "Marquette"},
    # Mason County (15)
    {"name": "Amber Township", "county": "Mason"},
    {"name": "Branch Township", "county": "Mason"},
    {"name": "Custer Township", "county": "Mason"},
    {"name": "Eden Township", "county": "Mason"},
    {"name": "Freesoil Township", "county": "Mason"},
    {"name": "Grant Township", "county": "Mason"},
    {"name": "Hamlin Township", "county": "Mason"},
    {"name": "Logan Township", "county": "Mason"},
    {"name": "Meade Township", "county": "Mason"},
    {"name": "Pere Marquette Township", "county": "Mason"},
    {"name": "Riverton Township", "county": "Mason"},
    {"name": "Sheridan Township", "county": "Mason"},
    {"name": "Sherman Township", "county": "Mason"},
    {"name": "Summit Township", "county": "Mason"},
    {"name": "Victory Township", "county": "Mason"},
    # Mecosta County (16)
    {"name": "Aetna Township", "county": "Mecosta"},
    {"name": "Austin Township", "county": "Mecosta"},
    {"name": "Big Rapids Township", "county": "Mecosta"},
    {"name": "Chippewa Township", "county": "Mecosta"},
    {"name": "Colfax Township", "county": "Mecosta"},
    {"name": "Deerfield Township", "county": "Mecosta"},
    {"name": "Fork Township", "county": "Mecosta"},
    {"name": "Grant Township", "county": "Mecosta"},
    {"name": "Green Township", "county": "Mecosta"},
    {"name": "Hinton Township", "county": "Mecosta"},
    {"name": "Martiny Township", "county": "Mecosta"},
    {"name": "Mecosta Township", "county": "Mecosta"},
    {"name": "Millbrook Township", "county": "Mecosta"},
    {"name": "Morton Township", "county": "Mecosta"},
    {"name": "Sheridan Township", "county": "Mecosta"},
    {"name": "Wheatland Township", "county": "Mecosta"},
    # Menominee County (14)
    {"name": "Cedarville Township", "county": "Menominee"},
    {"name": "Daggett Township", "county": "Menominee"},
    {"name": "Faithorn Township", "county": "Menominee"},
    {"name": "Gourley Township", "county": "Menominee"},
    {"name": "Harris Township", "county": "Menominee"},
    {"name": "Holmes Township", "county": "Menominee"},
    {"name": "Ingallston Township", "county": "Menominee"},
    {"name": "Lake Township", "county": "Menominee"},
    {"name": "Mellen Township", "county": "Menominee"},
    {"name": "Menominee Township", "county": "Menominee"},
    {"name": "Meyer Township", "county": "Menominee"},
    {"name": "Nadeau Township", "county": "Menominee"},
    {"name": "Spalding Township", "county": "Menominee"},
    {"name": "Stephenson Township", "county": "Menominee"},
    # Midland County (15)
    {"name": "Edenville Township", "county": "Midland"},
    {"name": "Geneva Township", "county": "Midland"},
    {"name": "Greendale Township", "county": "Midland"},
    {"name": "Homer Township", "county": "Midland"},
    {"name": "Hope Township", "county": "Midland"},
    {"name": "Ingersoll Township", "county": "Midland"},
    {"name": "Jasper Township", "county": "Midland"},
    {"name": "Jerome Township", "county": "Midland"},
    {"name": "Larkin Township", "county": "Midland"},
    {"name": "Lee Township", "county": "Midland"},
    {"name": "Lincoln Township", "county": "Midland"},
    {"name": "Midland Township", "county": "Midland"},
    {"name": "Mills Township", "county": "Midland"},
    {"name": "Mount Haley Township", "county": "Midland"},
    {"name": "Porter Township", "county": "Midland"},
    # Missaukee County (12)
    {"name": "Aetna Township", "county": "Missaukee"},
    {"name": "Bloomfield Township", "county": "Missaukee"},
    {"name": "Butterfield Township", "county": "Missaukee"},
    {"name": "Caldwell Township", "county": "Missaukee"},
    {"name": "Clam Union Township", "county": "Missaukee"},
    {"name": "Enterprise Township", "county": "Missaukee"},
    {"name": "Holland Township", "county": "Missaukee"},
    {"name": "Lake Township", "county": "Missaukee"},
    {"name": "Norwich Township", "county": "Missaukee"},
    {"name": "Pioneer Township", "county": "Missaukee"},
    {"name": "Reeder Township", "county": "Missaukee"},
    {"name": "Riverside Township", "county": "Missaukee"},
    # Monroe County (14)
    {"name": "Ash Township", "county": "Monroe"},
    {"name": "Bedford Township", "county": "Monroe"},
    {"name": "Berlin Township", "county": "Monroe"},
    {"name": "Dundee Township", "county": "Monroe"},
    {"name": "Erie Township", "county": "Monroe"},
    {"name": "Exeter Township", "county": "Monroe"},
    {"name": "Frenchtown Township", "county": "Monroe"},
    {"name": "Ida Township", "county": "Monroe"},
    {"name": "LaSalle Township", "county": "Monroe"},
    {"name": "London Township", "county": "Monroe"},
    {"name": "Milan Township", "county": "Monroe"},
    {"name": "Monroe Township", "county": "Monroe"},
    {"name": "Raisinville Township", "county": "Monroe"},
    {"name": "Summerfield Township", "county": "Monroe"},
    {"name": "Whiteford Township", "county": "Monroe"},
    # Montcalm County (19)
    {"name": "Belvidere Township", "county": "Montcalm"},
    {"name": "Bloomer Township", "county": "Montcalm"},
    {"name": "Bushnell Township", "county": "Montcalm"},
    {"name": "Cato Township", "county": "Montcalm"},
    {"name": "Crystal Township", "county": "Montcalm"},
    {"name": "Day Township", "county": "Montcalm"},
    {"name": "Douglass Township", "county": "Montcalm"},
    {"name": "Eureka Township", "county": "Montcalm"},
    {"name": "Evergreen Township", "county": "Montcalm"},
    {"name": "Fairplain Township", "county": "Montcalm"},
    {"name": "Ferris Township", "county": "Montcalm"},
    {"name": "Home Township", "county": "Montcalm"},
    {"name": "Maple Valley Township", "county": "Montcalm"},
    {"name": "Montcalm Township", "county": "Montcalm"},
    {"name": "Pierson Township", "county": "Montcalm"},
    {"name": "Pine Township", "county": "Montcalm"},
    {"name": "Reynolds Township", "county": "Montcalm"},
    {"name": "Richland Township", "county": "Montcalm"},
    {"name": "Sidney Township", "county": "Montcalm"},
    {"name": "Winfield Township", "county": "Montcalm"},
    # Montmorency County (8)
    {"name": "Albert Township", "county": "Montmorency"},
    {"name": "Avery Township", "county": "Montmorency"},
    {"name": "Briley Township", "county": "Montmorency"},
    {"name": "Hillman Township", "county": "Montmorency"},
    {"name": "Loud Township", "county": "Montmorency"},
    {"name": "Montmorency Township", "county": "Montmorency"},
    {"name": "Rust Township", "county": "Montmorency"},
    {"name": "Vienna Township", "county": "Montmorency"},
    # Muskegon County (15)
    {"name": "Blue Lake Township", "county": "Muskegon"},
    {"name": "Casnovia Township", "county": "Muskegon"},
    {"name": "Cedar Creek Township", "county": "Muskegon"},
    {"name": "Dalton Township", "county": "Muskegon"},
    {"name": "Egelston Township", "county": "Muskegon"},
    {"name": "Fruitland Township", "county": "Muskegon"},
    {"name": "Fruitport Township", "county": "Muskegon"},
    {"name": "Holton Township", "county": "Muskegon"},
    {"name": "Laketon Township", "county": "Muskegon"},
    {"name": "Montague Township", "county": "Muskegon"},
    {"name": "Moorland Township", "county": "Muskegon"},
    {"name": "Muskegon Township", "county": "Muskegon"},
    {"name": "Ravenna Township", "county": "Muskegon"},
    {"name": "Sullivan Township", "county": "Muskegon"},
    {"name": "White River Township", "county": "Muskegon"},
    {"name": "Whitehall Township", "county": "Muskegon"},
    # Newaygo County (24)
    {"name": "Ashland Township", "county": "Newaygo"},
    {"name": "Barton Township", "county": "Newaygo"},
    {"name": "Beaver Township", "county": "Newaygo"},
    {"name": "Big Prairie Township", "county": "Newaygo"},
    {"name": "Bridgeton Township", "county": "Newaygo"},
    {"name": "Brooks Township", "county": "Newaygo"},
    {"name": "Croton Township", "county": "Newaygo"},
    {"name": "Dayton Township", "county": "Newaygo"},
    {"name": "Denver Township", "county": "Newaygo"},
    {"name": "Ensley Township", "county": "Newaygo"},
    {"name": "Everett Township", "county": "Newaygo"},
    {"name": "Garfield Township", "county": "Newaygo"},
    {"name": "Goodwell Township", "county": "Newaygo"},
    {"name": "Grant Township", "county": "Newaygo"},
    {"name": "Home Township", "county": "Newaygo"},
    {"name": "Lilley Township", "county": "Newaygo"},
    {"name": "Lincoln Township", "county": "Newaygo"},
    {"name": "Merrill Township", "county": "Newaygo"},
    {"name": "Monroe Township", "county": "Newaygo"},
    {"name": "Norwich Township", "county": "Newaygo"},
    {"name": "Sheridan Township", "county": "Newaygo"},
    {"name": "Sherman Township", "county": "Newaygo"},
    {"name": "Troy Township", "county": "Newaygo"},
    {"name": "Wilcox Township", "county": "Newaygo"},
    # Oakland County (20)
    {"name": "Addison Township", "county": "Oakland"},
    {"name": "Bloomfield Township", "county": "Oakland"},
    {"name": "Brandon Township", "county": "Oakland"},
    {"name": "Commerce Township", "county": "Oakland"},
    {"name": "Groveland Township", "county": "Oakland"},
    {"name": "Highland Township", "county": "Oakland"},
    {"name": "Holly Township", "county": "Oakland"},
    {"name": "Independence Township", "county": "Oakland"},
    {"name": "Lyon Township", "county": "Oakland"},
    {"name": "Milford Township", "county": "Oakland"},
    {"name": "Novi Township", "county": "Oakland"},
    {"name": "Oakland Township", "county": "Oakland"},
    {"name": "Orion Township", "county": "Oakland"},
    {"name": "Oxford Township", "county": "Oakland"},
    {"name": "Rose Township", "county": "Oakland"},
    {"name": "Royal Oak Township", "county": "Oakland"},
    {"name": "Southfield Township", "county": "Oakland"},
    {"name": "Springfield Township", "county": "Oakland"},
    {"name": "Waterford Township", "county": "Oakland"},
    {"name": "West Bloomfield Township", "county": "Oakland"},
    {"name": "White Lake Township", "county": "Oakland"},
    # Oceana County (15)
    {"name": "Benona Township", "county": "Oceana"},
    {"name": "Claybanks Township", "county": "Oceana"},
    {"name": "Colfax Township", "county": "Oceana"},
    {"name": "Crystal Township", "county": "Oceana"},
    {"name": "Elbridge Township", "county": "Oceana"},
    {"name": "Ferry Township", "county": "Oceana"},
    {"name": "Golden Township", "county": "Oceana"},
    {"name": "Grant Township", "county": "Oceana"},
    {"name": "Greenwood Township", "county": "Oceana"},
    {"name": "Hart Township", "county": "Oceana"},
    {"name": "Leavitt Township", "county": "Oceana"},
    {"name": "Newfield Township", "county": "Oceana"},
    {"name": "Otto Township", "county": "Oceana"},
    {"name": "Pentwater Township", "county": "Oceana"},
    {"name": "Shelby Township", "county": "Oceana"},
    {"name": "Weare Township", "county": "Oceana"},
    # Ogemaw County (14)
    {"name": "Churchill Township", "county": "Ogemaw"},
    {"name": "Cumming Township", "county": "Ogemaw"},
    {"name": "Edwards Township", "county": "Ogemaw"},
    {"name": "Foster Township", "county": "Ogemaw"},
    {"name": "Goodar Township", "county": "Ogemaw"},
    {"name": "Hill Township", "county": "Ogemaw"},
    {"name": "Horton Township", "county": "Ogemaw"},
    {"name": "Klacking Township", "county": "Ogemaw"},
    {"name": "Logan Township", "county": "Ogemaw"},
    {"name": "Mills Township", "county": "Ogemaw"},
    {"name": "Ogemaw Township", "county": "Ogemaw"},
    {"name": "Richland Township", "county": "Ogemaw"},
    {"name": "Rose Township", "county": "Ogemaw"},
    {"name": "West Branch Township", "county": "Ogemaw"},
    # Ontonagon County (10)
    {"name": "Bergland Township", "county": "Ontonagon"},
    {"name": "Bohemia Township", "county": "Ontonagon"},
    {"name": "Carp Lake Township", "county": "Ontonagon"},
    {"name": "Greenland Township", "county": "Ontonagon"},
    {"name": "Interior Township", "county": "Ontonagon"},
    {"name": "Matchwood Township", "county": "Ontonagon"},
    {"name": "McMillan Township", "county": "Ontonagon"},
    {"name": "Ontonagon Township", "county": "Ontonagon"},
    {"name": "Rockland Township", "county": "Ontonagon"},
    {"name": "Stannard Township", "county": "Ontonagon"},
    # Osceola County (15)
    {"name": "Burdell Township", "county": "Osceola"},
    {"name": "Cedar Township", "county": "Osceola"},
    {"name": "Evart Township", "county": "Osceola"},
    {"name": "Hartwick Township", "county": "Osceola"},
    {"name": "Hersey Township", "county": "Osceola"},
    {"name": "Highland Township", "county": "Osceola"},
    {"name": "LeRoy Township", "county": "Osceola"},
    {"name": "Lincoln Township", "county": "Osceola"},
    {"name": "Marion Township", "county": "Osceola"},
    {"name": "Middle Branch Township", "county": "Osceola"},
    {"name": "Orient Township", "county": "Osceola"},
    {"name": "Osceola Township", "county": "Osceola"},
    {"name": "Richmond Township", "county": "Osceola"},
    {"name": "Rose Lake Township", "county": "Osceola"},
    {"name": "Sherman Township", "county": "Osceola"},
    {"name": "Sylvan Township", "county": "Osceola"},
    # Oscoda County (4)
    {"name": "Big Creek Township", "county": "Oscoda"},
    {"name": "Clinton Township", "county": "Oscoda"},
    {"name": "Elmer Township", "county": "Oscoda"},
    {"name": "Greenwood Township", "county": "Oscoda"},
    # Otsego County (9)
    {"name": "Bagley Township", "county": "Otsego"},
    {"name": "Charlton Township", "county": "Otsego"},
    {"name": "Chester Township", "county": "Otsego"},
    {"name": "Corwith Township", "county": "Otsego"},
    {"name": "Dover Township", "county": "Otsego"},
    {"name": "Elmira Township", "county": "Otsego"},
    {"name": "Hayes Township", "county": "Otsego"},
    {"name": "Livingston Township", "county": "Otsego"},
    {"name": "Otsego Lake Township", "county": "Otsego"},
    # Ottawa County (16)
    {"name": "Allendale Township", "county": "Ottawa"},
    {"name": "Blendon Township", "county": "Ottawa"},
    {"name": "Chester Township", "county": "Ottawa"},
    {"name": "Crockery Township", "county": "Ottawa"},
    {"name": "Georgetown Township", "county": "Ottawa"},
    {"name": "Grand Haven Township", "county": "Ottawa"},
    {"name": "Holland Township", "county": "Ottawa"},
    {"name": "Jamestown Township", "county": "Ottawa"},
    {"name": "Olive Township", "county": "Ottawa"},
    {"name": "Park Township", "county": "Ottawa"},
    {"name": "Polkton Township", "county": "Ottawa"},
    {"name": "Port Sheldon Township", "county": "Ottawa"},
    {"name": "Robinson Township", "county": "Ottawa"},
    {"name": "Spring Lake Township", "county": "Ottawa"},
    {"name": "Tallmadge Township", "county": "Ottawa"},
    {"name": "Wright Township", "county": "Ottawa"},
    {"name": "Zeeland Township", "county": "Ottawa"},
    # Presque Isle County (12)
    {"name": "Bearinger Township", "county": "Presque Isle"},
    {"name": "Belknap Township", "county": "Presque Isle"},
    {"name": "Bismarck Township", "county": "Presque Isle"},
    {"name": "Case Township", "county": "Presque Isle"},
    {"name": "Krakow Township", "county": "Presque Isle"},
    {"name": "Metz Township", "county": "Presque Isle"},
    {"name": "Moltke Township", "county": "Presque Isle"},
    {"name": "North Allis Township", "county": "Presque Isle"},
    {"name": "Ocqueoc Township", "county": "Presque Isle"},
    {"name": "Posen Township", "county": "Presque Isle"},
    {"name": "Presque Isle Township", "county": "Presque Isle"},
    {"name": "Pulawski Township", "county": "Presque Isle"},
    {"name": "Rogers Township", "county": "Presque Isle"},
    # Roscommon County (12)
    {"name": "Au Sable Township", "county": "Roscommon"},
    {"name": "Backus Township", "county": "Roscommon"},
    {"name": "Denton Township", "county": "Roscommon"},
    {"name": "Gerrish Township", "county": "Roscommon"},
    {"name": "Higgins Township", "county": "Roscommon"},
    {"name": "Lake Township", "county": "Roscommon"},
    {"name": "Lyon Township", "county": "Roscommon"},
    {"name": "Markey Township", "county": "Roscommon"},
    {"name": "Nester Township", "county": "Roscommon"},
    {"name": "Richfield Township", "county": "Roscommon"},
    {"name": "Roscommon Township", "county": "Roscommon"},
    # Saginaw County (26)
    {"name": "Albee Township", "county": "Saginaw"},
    {"name": "Birch Run Township", "county": "Saginaw"},
    {"name": "Blumfield Township", "county": "Saginaw"},
    {"name": "Brady Township", "county": "Saginaw"},
    {"name": "Brant Township", "county": "Saginaw"},
    {"name": "Bridgeport Township", "county": "Saginaw"},
    {"name": "Buena Vista Township", "county": "Saginaw"},
    {"name": "Carrollton Township", "county": "Saginaw"},
    {"name": "Chapin Township", "county": "Saginaw"},
    {"name": "Chesaning Township", "county": "Saginaw"},
    {"name": "Frankenmuth Township", "county": "Saginaw"},
    {"name": "James Township", "county": "Saginaw"},
    {"name": "Jonesfield Township", "county": "Saginaw"},
    {"name": "Kochville Township", "county": "Saginaw"},
    {"name": "Lakefield Township", "county": "Saginaw"},
    {"name": "Maple Grove Township", "county": "Saginaw"},
    {"name": "Marion Township", "county": "Saginaw"},
    {"name": "Richland Township", "county": "Saginaw"},
    {"name": "Saginaw Township", "county": "Saginaw"},
    {"name": "Spaulding Township", "county": "Saginaw"},
    {"name": "St. Charles Township", "county": "Saginaw"},
    {"name": "Swan Creek Township", "county": "Saginaw"},
    {"name": "Taymouth Township", "county": "Saginaw"},
    {"name": "Thomas Township", "county": "Saginaw"},
    {"name": "Tittabawassee Township", "county": "Saginaw"},
    {"name": "Zilwaukee Township", "county": "Saginaw"},
    # Sanilac County (26)
    {"name": "Argyle Township", "county": "Sanilac"},
    {"name": "Austin Township", "county": "Sanilac"},
    {"name": "Bridgehampton Township", "county": "Sanilac"},
    {"name": "Buel Township", "county": "Sanilac"},
    {"name": "Custer Township", "county": "Sanilac"},
    {"name": "Delaware Township", "county": "Sanilac"},
    {"name": "Elk Township", "county": "Sanilac"},
    {"name": "Elmer Township", "county": "Sanilac"},
    {"name": "Evergreen Township", "county": "Sanilac"},
    {"name": "Flynn Township", "county": "Sanilac"},
    {"name": "Forester Township", "county": "Sanilac"},
    {"name": "Fremont Township", "county": "Sanilac"},
    {"name": "Greenleaf Township", "county": "Sanilac"},
    {"name": "Lamotte Township", "county": "Sanilac"},
    {"name": "Lexington Township", "county": "Sanilac"},
    {"name": "Maple Valley Township", "county": "Sanilac"},
    {"name": "Marion Township", "county": "Sanilac"},
    {"name": "Marlette Township", "county": "Sanilac"},
    {"name": "Minden Township", "county": "Sanilac"},
    {"name": "Moore Township", "county": "Sanilac"},
    {"name": "Sanilac Township", "county": "Sanilac"},
    {"name": "Speaker Township", "county": "Sanilac"},
    {"name": "Washington Township", "county": "Sanilac"},
    {"name": "Watertown Township", "county": "Sanilac"},
    {"name": "Wheatland Township", "county": "Sanilac"},
    {"name": "Worth Township", "county": "Sanilac"},
    # Schoolcraft County (7)
    {"name": "Doyle Township", "county": "Schoolcraft"},
    {"name": "Germfask Township", "county": "Schoolcraft"},
    {"name": "Hiawatha Township", "county": "Schoolcraft"},
    {"name": "Inwood Township", "county": "Schoolcraft"},
    {"name": "Manistique Township", "county": "Schoolcraft"},
    {"name": "Mueller Township", "county": "Schoolcraft"},
    {"name": "Thompson Township", "county": "Schoolcraft"},
    # Shiawassee County (13)
    {"name": "Antrim Township", "county": "Shiawassee"},
    {"name": "Bennington Township", "county": "Shiawassee"},
    {"name": "Burns Township", "county": "Shiawassee"},
    {"name": "Caledonia Township", "county": "Shiawassee"},
    {"name": "Fairfield Township", "county": "Shiawassee"},
    {"name": "Hazelton Township", "county": "Shiawassee"},
    {"name": "Middlebury Township", "county": "Shiawassee"},
    {"name": "New Haven Township", "county": "Shiawassee"},
    {"name": "Owosso Township", "county": "Shiawassee"},
    {"name": "Perry Township", "county": "Shiawassee"},
    {"name": "Rush Township", "county": "Shiawassee"},
    {"name": "Sciota Township", "county": "Shiawassee"},
    {"name": "Shiawassee Township", "county": "Shiawassee"},
    {"name": "Venice Township", "county": "Shiawassee"},
    {"name": "Vernon Township", "county": "Shiawassee"},
    {"name": "Woodhull Township", "county": "Shiawassee"},
    # St. Clair County (23)
    {"name": "Berlin Township", "county": "St. Clair"},
    {"name": "Brockway Township", "county": "St. Clair"},
    {"name": "Burtchville Township", "county": "St. Clair"},
    {"name": "Casco Township", "county": "St. Clair"},
    {"name": "China Township", "county": "St. Clair"},
    {"name": "Clay Township", "county": "St. Clair"},
    {"name": "Clyde Township", "county": "St. Clair"},
    {"name": "Columbus Township", "county": "St. Clair"},
    {"name": "Cottrellville Township", "county": "St. Clair"},
    {"name": "East China Township", "county": "St. Clair"},
    {"name": "Emmett Township", "county": "St. Clair"},
    {"name": "Fort Gratiot Township", "county": "St. Clair"},
    {"name": "Grant Township", "county": "St. Clair"},
    {"name": "Greenwood Township", "county": "St. Clair"},
    {"name": "Ira Township", "county": "St. Clair"},
    {"name": "Kenockee Township", "county": "St. Clair"},
    {"name": "Kimball Township", "county": "St. Clair"},
    {"name": "Lynn Township", "county": "St. Clair"},
    {"name": "Mussey Township", "county": "St. Clair"},
    {"name": "Port Huron Township", "county": "St. Clair"},
    {"name": "Riley Township", "county": "St. Clair"},
    {"name": "St. Clair Township", "county": "St. Clair"},
    {"name": "Wales Township", "county": "St. Clair"},
    # St. Joseph County (15)
    {"name": "Burr Oak Township", "county": "St. Joseph"},
    {"name": "Colon Township", "county": "St. Joseph"},
    {"name": "Constantine Township", "county": "St. Joseph"},
    {"name": "Fabius Township", "county": "St. Joseph"},
    {"name": "Fawn River Township", "county": "St. Joseph"},
    {"name": "Florence Township", "county": "St. Joseph"},
    {"name": "Flowerfield Township", "county": "St. Joseph"},
    {"name": "Leonidas Township", "county": "St. Joseph"},
    {"name": "Lockport Township", "county": "St. Joseph"},
    {"name": "Mendon Township", "county": "St. Joseph"},
    {"name": "Mottville Township", "county": "St. Joseph"},
    {"name": "Park Township", "county": "St. Joseph"},
    {"name": "Sherman Township", "county": "St. Joseph"},
    {"name": "Sturgis Township", "county": "St. Joseph"},
    {"name": "White Pigeon Township", "county": "St. Joseph"},
    # Tuscola County (23)
    {"name": "Akron Township", "county": "Tuscola"},
    {"name": "Almer Township", "county": "Tuscola"},
    {"name": "Arbela Township", "county": "Tuscola"},
    {"name": "Columbia Township", "county": "Tuscola"},
    {"name": "Dayton Township", "county": "Tuscola"},
    {"name": "Denmark Township", "county": "Tuscola"},
    {"name": "Elkland Township", "county": "Tuscola"},
    {"name": "Ellington Township", "county": "Tuscola"},
    {"name": "Elmwood Township", "county": "Tuscola"},
    {"name": "Fairgrove Township", "county": "Tuscola"},
    {"name": "Fremont Township", "county": "Tuscola"},
    {"name": "Gilford Township", "county": "Tuscola"},
    {"name": "Indianfields Township", "county": "Tuscola"},
    {"name": "Juniata Township", "county": "Tuscola"},
    {"name": "Kingston Township", "county": "Tuscola"},
    {"name": "Koylton Township", "county": "Tuscola"},
    {"name": "Millington Township", "county": "Tuscola"},
    {"name": "Novesta Township", "county": "Tuscola"},
    {"name": "Tuscola Township", "county": "Tuscola"},
    {"name": "Vassar Township", "county": "Tuscola"},
    {"name": "Watertown Township", "county": "Tuscola"},
    {"name": "Wells Township", "county": "Tuscola"},
    {"name": "Wisner Township", "county": "Tuscola"},
    # Van Buren County (17)
    {"name": "Almena Township", "county": "Van Buren"},
    {"name": "Antwerp Township", "county": "Van Buren"},
    {"name": "Arlington Township", "county": "Van Buren"},
    {"name": "Bangor Township", "county": "Van Buren"},
    {"name": "Bloomingdale Township", "county": "Van Buren"},
    {"name": "Columbia Township", "county": "Van Buren"},
    {"name": "Covert Township", "county": "Van Buren"},
    {"name": "Decatur Township", "county": "Van Buren"},
    {"name": "Geneva Township", "county": "Van Buren"},
    {"name": "Hamilton Township", "county": "Van Buren"},
    {"name": "Hartford Township", "county": "Van Buren"},
    {"name": "Keeler Township", "county": "Van Buren"},
    {"name": "Lawrence Township", "county": "Van Buren"},
    {"name": "Paw Paw Township", "county": "Van Buren"},
    {"name": "Pine Grove Township", "county": "Van Buren"},
    {"name": "Porter Township", "county": "Van Buren"},
    {"name": "South Haven Township", "county": "Van Buren"},
    {"name": "Waverly Township", "county": "Van Buren"},
    # Washtenaw County (20)
    {"name": "Ann Arbor Township", "county": "Washtenaw"},
    {"name": "Augusta Township", "county": "Washtenaw"},
    {"name": "Bridgewater Township", "county": "Washtenaw"},
    {"name": "Dexter Township", "county": "Washtenaw"},
    {"name": "Freedom Township", "county": "Washtenaw"},
    {"name": "Lima Township", "county": "Washtenaw"},
    {"name": "Lodi Township", "county": "Washtenaw"},
    {"name": "Lyndon Township", "county": "Washtenaw"},
    {"name": "Manchester Township", "county": "Washtenaw"},
    {"name": "Northfield Township", "county": "Washtenaw"},
    {"name": "Pittsfield Township", "county": "Washtenaw"},
    {"name": "Salem Township", "county": "Washtenaw"},
    {"name": "Saline Township", "county": "Washtenaw"},
    {"name": "Scio Township", "county": "Washtenaw"},
    {"name": "Sharon Township", "county": "Washtenaw"},
    {"name": "Superior Township", "county": "Washtenaw"},
    {"name": "Sylvan Township", "county": "Washtenaw"},
    {"name": "Webster Township", "county": "Washtenaw"},
    {"name": "York Township", "county": "Washtenaw"},
    {"name": "Ypsilanti Township", "county": "Washtenaw"},
    # Wayne County (10)
    {"name": "Brownstown Township", "county": "Wayne"},
    {"name": "Canton Township", "county": "Wayne"},
    {"name": "Grosse Ile Township", "county": "Wayne"},
    {"name": "Huron Township", "county": "Wayne"},
    {"name": "Northville Township", "county": "Wayne"},
    {"name": "Plymouth Township", "county": "Wayne"},
    {"name": "Redford Township", "county": "Wayne"},
    {"name": "Sumpter Township", "county": "Wayne"},
    {"name": "Van Buren Township", "county": "Wayne"},
    # Wexford County (13)
    {"name": "Antioch Township", "county": "Wexford"},
    {"name": "Boon Township", "county": "Wexford"},
    {"name": "Cedar Creek Township", "county": "Wexford"},
    {"name": "Cherry Grove Township", "county": "Wexford"},
    {"name": "Clam Lake Township", "county": "Wexford"},
    {"name": "Colfax Township", "county": "Wexford"},
    {"name": "Hanover Township", "county": "Wexford"},
    {"name": "Haring Township", "county": "Wexford"},
    {"name": "Henderson Township", "county": "Wexford"},
    {"name": "Liberty Township", "county": "Wexford"},
    {"name": "Selma Township", "county": "Wexford"},
    {"name": "Slagle Township", "county": "Wexford"},
    {"name": "Springville Township", "county": "Wexford"},
    {"name": "Wexford Township", "county": "Wexford"},
]
# fmt: on


def main() -> None:
    conn = get_connection()
    created = 0
    skipped = 0
    errors = 0

    try:
        with get_cursor(conn) as cur:
            # Build county lookup: name -> id
            cur.execute('SELECT id, name FROM "County" ORDER BY name')
            rows = cur.fetchall()
            if not rows:
                print("ERROR: No counties found in database. Run county seed first.")
                sys.exit(1)

            county_map: dict[str, str] = {}
            for r in rows:
                county_map[r["name"]] = r["id"]
            print(f"Found {len(county_map)} counties in database")

            for t in TOWNSHIPS:
                name = t["name"]
                county_name = t["county"]
                slug = slugify(name)
                entity_id = f"ent_{slug}"

                county_id = county_map.get(county_name)
                if county_id is None:
                    print(f"  WARNING: county '{county_name}' not found for {name}")
                    errors += 1
                    continue

                # For duplicate slugs across counties, append county
                cur.execute(
                    'SELECT id FROM "Entity" WHERE slug = %s', (slug,)
                )
                existing = cur.fetchone()
                if existing:
                    # Make slug unique by appending county
                    slug = slugify(f"{name} {county_name}")
                    entity_id = f"ent_{slug}"

                cur.execute(
                    """
                    INSERT INTO "Entity" (
                        id, name, slug, type, platform, "countyId",
                        "scrapeStatus", "scrapeFrequency", "isCharter",
                        "createdAt", "updatedAt"
                    ) VALUES (
                        %s, %s, %s, 'TOWNSHIP', 'UNKNOWN', %s,
                        'PENDING', 24, false,
                        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    )
                    ON CONFLICT (slug) DO NOTHING
                    RETURNING id
                    """,
                    (entity_id, name, slug, county_id),
                )
                row = cur.fetchone()
                if row:
                    created += 1
                else:
                    skipped += 1

                if (created + skipped + errors) % 100 == 0:
                    print(f"  ... processed {created + skipped + errors} townships")

        print(f"\nTownship entities: {created} created, {skipped} already existed, {errors} errors")
        print(f"Total townships in list: {len(TOWNSHIPS)}")

    finally:
        conn.close()


if __name__ == "__main__":
    main()
